const types = {
	FETCH_USER: "FETCH_USER",

	FETCH_CLIENT: "FETCH_CLIENT",

	AUDIT_CYCLE_GET: "AUDIT_CYCLE_GET",
	AUDIT_CYCLE_FORM_LOAD: "AUDIT_CYCLE_FORM_LOAD",
	AUDIT_CYCLE_POST: "AUDIT_CYCLE_POST",
	AUDIT_CYCLE_FORM_SUB: "AUDIT_CYCLE_FORM_SUB",
	AUDIT_CYCLE_ID_GET: "AUDIT_CYCLE_ID_GET",
	AUDIT_CYCLE_ID_POST: "AUDIT_CYCLE_ID_POST",

	AUDIT_GET: "AUDIT_GET",
	AUDIT_ID_GET: "AUDIT_ID_GET",
	AUDIT_POST: "AUDIT_POST",
	AUDIT_ID_POST: "AUDIT_ID_POST",
	AUDIT_ID_DELETE: "AUDIT_ID_DELETE",
	AUDIT_FORM_SUB: "AUDIT_FORM_SUB",
	AUDIT_FORM_LOAD: "AUDIT_FORM_LOAD",

	STORE_GET: "STORE_GET",
	STORE_ID_GET: "STORE_ID_GET",
	STORE_ID_DELETE: "STORE_ID_DELETE",
	STORE_FORM_LOAD: "STORE_FORM_LOAD",
	STORE_FORM_SUB: "STORE_FORM_SUB",
	STORE_POST: "STORE_POST",
	STORE_ID_POST: "STORE_ID_POST",
	STORE_UPDATED: "STORE_UPDATED",

	SET_FORM_ERRORS: "SET_FORM_ERRORS",
	RESET_FORM_ERRORS: "RESET_FORM_ERRORS",

	SECTION_GET: "SECTION_GET",
	SECTION_ID_GET: "SECTION_ID_GET",
	SECTION_POST: "SECTION_POST",
	SECTION_ID_POST: "SECTION_ID_POST",
	SECTION_ID_DELETE: "SECTION_ID_DELETE",

	COUNTRY_GET: "COUNTRY_GET",
	STATE_GET: "STATE_GET",
	STATE_GET_BY_COUNTRY: "STATE_GET_BY_COUNTRY",
	CITY_GET: "CITY_GET",

	CLIENT_USER_GET: "CLIENT_USER_GET",
	CLIENT_USER_ID_GET: "CLIENT_USER_ID_GET",
	CLIENT_USER_FORM_LOAD: "CLIENT_USER_FORM_LOAD",
	CLIENT_USER_FORM_SUB: "CLIENT_USER_FORM_SUB",
	CLIENT_USER_POST: "CLIENT_USER_POST",
	CLIENT_USER_ID_POST: "CLIENT_USER_ID_POST",
	CLIENT_USER_STORE_VISIBILITY: "CLIENT_USER_STORE_VISIBILITY",

	FETCH_ACCOUNT_BALANCE: "FETCH_ACCOUNT_BALANCE",

	FIND_UNCOMPLETE_QUOTATION: "FIND_UNCOMPLETE_QUOTATION",
};

export default types;
