# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-03-31 07:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('amount', models.FloatField(db_column='amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], db_column='status', default='CREATED', max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('added_on', models.DateTimeField(auto_now_add=True, db_column='added_on')),
                ('paid_on', models.DateTimeField(db_column='paid_on', null=True)),
                ('payment_data', django.contrib.postgres.fields.jsonb.JSONField(db_column='payment_data', default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
        ),
    ]
