# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-03-31 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_order_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
