# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-04-04 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_payment_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gst',
            field=models.DecimalField(db_column='gst', decimal_places=1, default=18, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(db_column='amount', decimal_places=1, max_digits=10),
        ),
    ]
