# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='auditlocation',
            name='auditLocation',
        ),
        migrations.AddField(
            model_name='auditlocation',
            name='location',
            field=models.ForeignKey(db_column='location_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='client.Location'),
            preserve_default=False,
        ),
    ]
