# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_logo_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientuser',
            options={'permissions': (('clientuser_admin', 'ClientUser can view all reports, the dashboard and access related reporting APIs'),)},
        ),
    ]
