# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20170725_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='client',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='client.Client'),
        ),
    ]
