# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20170829_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='client',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='client.Client'),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.PROTECT, to='manager.Location'),
        ),
    ]
