# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20170829_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='code',
            field=models.CharField(blank=True, db_column='code', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='store',
            name='priority',
            field=models.CharField(blank=True, db_column='priority', max_length=5),
        ),
        migrations.AddField(
            model_name='store',
            name='type',
            field=models.CharField(blank=True, db_column='type', max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(db_column='name', max_length=500),
        ),
    ]
