# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-22 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20170915_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(blank=True, db_column='code', default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='priority',
            field=models.CharField(blank=True, db_column='priority', default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='store',
            name='type',
            field=models.CharField(blank=True, db_column='type', default='', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together=set([('client', 'code')]),
        ),
    ]
