# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-09 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20170922_0301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'permissions': (('clientuser_store_visible', 'ClientUser can view all AuditStore instances for this Store'),)},
        ),
    ]
