# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-13 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20171009_0551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
    ]
