# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-09 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20171113_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, db_column='phone', max_length=15),
        ),
    ]
