# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-10 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_store_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='brand_logo_url',
            field=models.CharField(blank=True, db_column='brand_logo_url', max_length=512),
        ),
        migrations.AddField(
            model_name='client',
            name='brand_name',
            field=models.CharField(blank=True, db_column='brand_name', max_length=50),
        ),
    ]
