# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-15 12:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20171210_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_column='extra_data', default={}),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, db_column='phone', max_length=100),
        ),
    ]
