# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-18 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20170829_1043'),
        ('client', '0013_auto_20171215_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.ForeignKey(db_column='city_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.City'),
        ),
    ]
