# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_auto_20180109_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='priority',
            field=models.CharField(blank=True, db_column='priority', default='', max_length=50),
        ),
    ]
