# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20180615_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(db_column='created_at', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='modified_at',
            field=models.DateTimeField(db_column='modified_at', null=True),
        ),
    ]
