# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 17:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_auto_20180615_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_column='extra_data', default=dict),
        ),
    ]
