# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-30 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_auto_20181020_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='receive_email_notification',
            field=models.BooleanField(db_column='receive_email_notification', default=True),
        ),
    ]
