# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-17 11:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_clientmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmanager',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
