# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-18 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_auto_20200717_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientmanager',
            options={'ordering': ['id']},
        ),
    ]
