# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-04 12:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_auto_20200718_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonClientAdminUserStore',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('stores', django.contrib.postgres.fields.jsonb.JSONField(db_column='stores', default=dict)),
                ('created_at', models.DateTimeField(db_column='created_at', null=True)),
                ('modified_at', models.DateTimeField(db_column='modified_at', null=True)),
                ('client_user', models.ForeignKey(db_column='client_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='non_admin_user_store_list', to='client.ClientUser')),
            ],
        ),
    ]
