# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-31 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0023_nonclientadminuserstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='receive_email_notification',
            field=models.BooleanField(db_column='receive_email_notification', default=True),
        ),
    ]
