# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-03-24 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_clienttrainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('gstin', models.CharField(blank=True, db_column='gstin', max_length=20)),
                ('pan_number', models.CharField(blank=True, db_column='pan_number', max_length=10)),
                ('created_at', models.DateTimeField(db_column='created_at', null=True)),
                ('modified_at', models.DateTimeField(db_column='modified_at', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, db_column='address', max_length=300),
        ),
        migrations.AddField(
            model_name='client',
            name='company_website_url',
            field=models.CharField(blank=True, db_column='company_website_url', max_length=200),
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='client',
            field=models.OneToOneField(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='client_bank_info', to='client.Client'),
        ),
    ]
