# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-03-24 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0026_auto_20220324_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_auto_signup',
            field=models.BooleanField(db_column='is_auto_signup', default=False),
        ),
    ]
