# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-04-13 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0027_client_is_auto_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='map_location_link',
            field=models.CharField(blank=True, db_column='map_location_link', default='', max_length=1024),
        ),
    ]
