# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-05-20 10:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0028_store_map_location_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('quotation_data', django.contrib.postgres.fields.jsonb.JSONField(db_column='quotation_data', default=dict)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending')], db_column='status', max_length=10)),
                ('created_at', models.DateTimeField(db_column='created_at', null=True)),
                ('modified_at', models.DateTimeField(db_column='modified_at', null=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='quotation', to='client.Client')),
            ],
        ),
    ]
