# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-06-17 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0029_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='pincode',
            field=models.CharField(blank=True, db_column='pincode', default=None, max_length=20, null=True),
        ),
    ]
