# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-07-15 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0015_auto_20220715_1038'),
        ('client', '0030_store_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='amount',
            field=models.DecimalField(db_column='amount', decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount',
            field=models.DecimalField(db_column='discount', decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='gst',
            field=models.DecimalField(db_column='gst', decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='industry',
            field=models.ForeignKey(db_column='industry_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='quotation', to='questionnaire.Industry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='payable_amount',
            field=models.DecimalField(db_column='payable_amount', decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='problem_statement',
            field=models.ForeignKey(db_column='problem_statement_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='quotation', to='questionnaire.ProblemStatement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='sample_questionnaire_type',
            field=models.ForeignKey(db_column='sample_questionnaire_type_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='quotation', to='questionnaire.SampleQuestionnaireType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed')], db_column='status', max_length=10),
        ),
    ]
