# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-04-24 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0031_auto_20220715_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, db_column='city', max_length=300),
        ),
        migrations.AddField(
            model_name='client',
            name='gst_in',
            field=models.CharField(blank=True, db_column='gst_in', max_length=300),
        ),
        migrations.AddField(
            model_name='client',
            name='pincode',
            field=models.CharField(blank=True, db_column='pincode', max_length=300),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, db_column='state', max_length=300),
        ),
    ]
