# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-04-25 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0032_auto_20230424_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientForEcomm',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_column='first_name', max_length=50)),
                ('last_name', models.CharField(blank=True, db_column='last_name', max_length=50)),
                ('email', models.EmailField(db_column='email', max_length=50)),
                ('phone_number', models.CharField(blank=True, db_column='phone_number', max_length=15)),
                ('company', models.CharField(blank=True, db_column='company', max_length=50)),
                ('password', models.CharField(blank=True, db_column='password', max_length=50)),
                ('encrypt_password', models.CharField(blank=True, db_column='encrypt_password', max_length=50)),
                ('address', models.CharField(blank=True, db_column='address', max_length=50)),
                ('city', models.CharField(blank=True, db_column='city', max_length=50)),
                ('state', models.CharField(blank=True, db_column='state', max_length=50)),
                ('pincode', models.CharField(blank=True, db_column='pincode', max_length=50)),
                ('gst_in', models.CharField(blank=True, db_column='gst_in', max_length=50)),
                ('created_at', models.DateTimeField(db_column='created_at', null=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
