# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-04-25 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0033_clientforecomm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientforecomm',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='clientforecomm',
            name='encrypt_password',
            field=models.CharField(blank=True, db_column='encrypt_password', max_length=350),
        ),
    ]
