# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-04-25 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0034_auto_20230425_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientforecomm',
            name='created_at',
            field=models.DateTimeField(db_column='created_at', null=True),
        ),
    ]
