# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-04-25 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0035_clientforecomm_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientforecomm',
            name='encrypt_password',
            field=models.CharField(blank=True, db_column='encrypt_password', max_length=128),
        ),
    ]
