# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-11 05:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0036_auto_20230425_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPClientProfileInfo',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_column='phone_number', max_length=15)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
