# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-11 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0037_mpclientprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpclientprofileinfo',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='mpclientprofileinfo',
            name='mobile_number',
            field=models.CharField(db_column='mobile_number', default=1, max_length=15),
            preserve_default=False,
        ),
    ]
