# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-15 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0038_auto_20230711_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpclientprofileinfo',
            name='company_name',
            field=models.CharField(db_column='company_name', default='f', max_length=15),
            preserve_default=False,
        ),
    ]
