# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-18 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0039_mpclientprofileinfo_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpclientprofileinfo',
            name='first_name',
            field=models.CharField(db_column='first_name', default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpclientprofileinfo',
            name='last_name',
            field=models.CharField(blank=True, db_column='last_name', max_length=150),
        ),
    ]
