# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-18 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0040_auto_20230718_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpclientprofileinfo',
            name='last_name',
            field=models.CharField(blank=True, db_column='last_name', default='', max_length=150),
        ),
    ]
