# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-19 07:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0041_auto_20230718_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpclientprofileinfo',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
