# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-08-04 10:39
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0074_auto_20230804_1609'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0043_client_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPOrder',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('no_of_response', models.IntegerField(blank=True, db_column='no_of_response', default=1)),
                ('describe', models.CharField(blank=True, db_column='describe', max_length=16384)),
                ('status', models.CharField(choices=[('COMPLETE', 'Complete'), ('DRAFT', 'Draft'), ('ACTIVE', 'Active')], db_column='status', max_length=20)),
                ('alignment_factors', django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='alignment_factors', default=list)),
                ('store', django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='stores', default=list)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(db_column='price', max_length=20)),
                ('solution', models.ForeignKey(db_column='solution_id', on_delete=django.db.models.deletion.PROTECT, related_name='mporders', to='manager.MPSolution')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_id', models.CharField(db_column='payment_id', max_length=100)),
                ('signature', models.CharField(db_column='signature', max_length=200)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='client.MPOrder')),
            ],
        ),
    ]
