# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-08-11 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0044_mporder_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mporder',
            name='price',
            field=models.IntegerField(blank=True, db_column='price', default=0, null=True),
        ),
    ]
