# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-08-11 11:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0045_auto_20230811_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mporder',
            name='alignment_factors',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='alignment_factors', default=list, null=True),
        ),
        migrations.AlterField(
            model_name='mporder',
            name='describe',
            field=models.CharField(blank=True, db_column='describe', max_length=16384, null=True),
        ),
        migrations.AlterField(
            model_name='mporder',
            name='no_of_response',
            field=models.IntegerField(blank=True, db_column='no_of_response', default=1, null=True),
        ),
        migrations.AlterField(
            model_name='mporder',
            name='store',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='stores', default=list, null=True),
        ),
    ]
