# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-08-23 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0046_auto_20230811_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_success_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
