# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-08-23 05:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0047_transaction_payment_success_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='extra_data', default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='map_location_link',
            field=models.CharField(blank=True, db_column='map_location_link', default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='priority',
            field=models.CharField(blank=True, db_column='priority', default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='type',
            field=models.CharField(blank=True, db_column='type', default='', max_length=20, null=True),
        ),
    ]
