# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-09-12 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0081_auto_20230831_1050'),
        ('client', '0049_auto_20230823_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='mporder',
            name='category',
            field=models.ForeignKey(db_column='category_id', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mporders', to='manager.MPCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_success_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
