# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-09-13 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0050_auto_20230912_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpclientprofileinfo',
            name='gst',
            field=models.CharField(blank=True, db_column='gst', default='', max_length=150),
        ),
    ]
