# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-09-18 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0051_mpclientprofileinfo_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='mporder',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('SUCCESS', 'Payment Successful'), ('FAILED', 'Payment Failed')], db_column='payment_status', max_length=20, null=True),
        ),
    ]
