# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-09-20 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0052_mporder_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpclientprofileinfo',
            name='address',
            field=models.CharField(blank=True, db_column='address', default='', max_length=150),
        ),
    ]
