# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-09-21 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0053_mpclientprofileinfo_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='mporder',
            name='created_at',
            field=models.DateTimeField(blank=True, db_column='created_at', null=True),
        ),
        migrations.AddField(
            model_name='mporder',
            name='modified_at',
            field=models.DateTimeField(blank=True, db_column='modified_at', null=True),
        ),
    ]
