# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-09-26 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0054_auto_20230921_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.PROTECT, to='client.MPOrder'),
        ),
    ]
