# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-09-26 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0055_auto_20230926_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpclientprofileinfo',
            name='company_name',
        ),
        migrations.AddField(
            model_name='mpclientprofileinfo',
            name='brand',
            field=models.CharField(db_column='brand', default='brand', max_length=15),
            preserve_default=False,
        ),
    ]
