# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-09-28 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0056_merge_20230926_2125'),
        ('client', '0056_auto_20230926_1652'),
    ]

    operations = [
    ]
