# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-10-03 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0057_merge_20230928_0952'),
        ('client', '0057_merge_20230927_1822'),
    ]

    operations = [
    ]
