# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-10-03 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0058_merge_20231003_1258'),
        ('client', '0058_merge_20231003_1301'),
    ]

    operations = [
    ]
