# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-10-06 06:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0059_merge_20231003_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequirements',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=25)),
                ('start_date', models.DateField(db_column='start_date')),
                ('end_date', models.DateField(db_column='end_date')),
                ('problem_statement', models.CharField(db_column='problem_statement', max_length=16384)),
                ('type', models.CharField(choices=[('MYSTERY_AUDIT_PURCHASE_AND_OR_NON_PURCHASE', 'Mystery Audit (Purchase and/or Non-Purchase)'), ('REVEALED_AUDITS', 'Revealed Audits'), ('MYSTERY_REVEALED_AUDIT_PURCHASE_AND_OR_NON_PURCHASE', 'Mystery Revealed Audit (Purchase and/or Non-Purchase)')], db_column='type', max_length=100)),
                ('audit_count_with_type', django.contrib.postgres.fields.jsonb.JSONField(db_column='audit_count_with_type', default=dict)),
                ('category', models.CharField(choices=[('CONSUMER_EXPERIENCE_AND_JOURNEY', 'Consumer Experience and Journey'), ('SALES_PROCESS', 'Sales Process'), ('VISUAL_MERCHANDISING', 'Visual Mechandising'), ('COMPETITION_BENCHMARKING', 'Competition Benchmarking'), ('PROCESS_COMPLIANCE_AUDITS', 'Process Compliance Audits'), ('RETAILER_RECOMMENDATION_PROGRAM', 'Retailer Recommendation Program'), ('INVENTORY_AUDITS', 'Inventory Audits')], db_column='category', max_length=100)),
                ('questionnaire_type', models.CharField(choices=[('WED', 'Web'), ('TELEPHONIC', 'Telephonic'), ('VISIT', 'Visit')], db_column='questionnaire_type', max_length=100)),
                ('setup_fee', models.IntegerField(blank=True, db_column='setup_fee', null=True)),
                ('price_per_audit', models.IntegerField(blank=True, db_column='price_per_audit', null=True)),
                ('execution_budget', models.IntegerField(blank=True, db_column='execution_budget', null=True)),
                ('scope_of_work', models.CharField(db_column='scope_of_work', max_length=16384)),
                ('audit_flow', models.CharField(db_column='audit_flow', max_length=16384)),
                ('project_manager_email', models.EmailField(db_column='project_manager_email', max_length=50)),
                ('sales_representative_email', models.EmailField(db_column='sales_representative_email', max_length=50)),
                ('created_at', models.DateTimeField(db_column='created_at', null=True)),
                ('modified_at', models.DateTimeField(db_column='modified_at', null=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='client_requirements', to='client.Client')),
            ],
        ),
    ]
