# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-10-10 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0060_clientrequirements'),
        ('client', '0059_merge_20231003_1509'),
    ]

    operations = [
    ]
