# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-05-07 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0061_merge_20231010_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='mporder',
            name='country_code',
            field=models.CharField(db_column='country_code', default=1, max_length=20),
            preserve_default=False,
        ),
    ]
