# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-05-07 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0062_mporder_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mporder',
            name='country_code',
            field=models.CharField(blank=True, db_column='country_code', max_length=20, null=True),
        ),
    ]
