# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-02-21 10:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0063_auto_20240507_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateCityMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cities', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_mappings', to='client.Client')),
                ('mp_order', models.ForeignKey(db_column='mp_order_id', on_delete=django.db.models.deletion.CASCADE, to='client.MPOrder')),
            ],
        ),
    ]
