# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-02-21 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0064_statecitymapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statecitymapping',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='state_mappings', to='client.Client'),
        ),
        migrations.AlterField(
            model_name='statecitymapping',
            name='mp_order',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='client.MPOrder'),
        ),
    ]
