# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-02-24 08:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0065_auto_20250221_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='mporder',
            name='state_city_map',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='state_city_map', default=list, null=True),
        ),
    ]
