# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-08-12 06:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0067_clientmoderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidgetvisibilityAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_audit_cycle_score', models.BooleanField(db_column='latest_audit_cycle_score', default=True)),
                ('upcoming_audits', models.BooleanField(db_column='upcoming_audits', default=True)),
                ('net_promoter_score', models.BooleanField(db_column='net_promoter_score', default=True)),
                ('section_summary', models.BooleanField(db_column='section_summary', default=True)),
                ('improvement_areas_based_on_observation', models.BooleanField(db_column='improvement_areas_based_on_observation', default=True)),
                ('overall_high_performance_store', models.BooleanField(db_column='overall_high_performance_store', default=True)),
                ('branch_performance', models.BooleanField(db_column='branch_performance', default=True)),
                ('overall_high_performance_city', models.BooleanField(db_column='overall_high_performance_city', default=True)),
                ('overall_low_performance_store', models.BooleanField(db_column='overall_low_performance_store', default=True)),
                ('overall_low_performance_city', models.BooleanField(db_column='overall_low_performance_city', default=True)),
                ('questionnaire_summary', models.BooleanField(db_column='questionnaire_summary', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='background_image_url',
            field=models.CharField(blank=True, db_column='background_image_url', max_length=2512),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_color',
            field=models.CharField(blank=True, db_column='primary_color', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='score_scale',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='score_scale', default=dict),
        ),
        migrations.AddField(
            model_name='client',
            name='secondary_color',
            field=models.CharField(blank=True, db_column='secondary_color', max_length=50),
        ),
        migrations.AddField(
            model_name='dashboardwidgetvisibilityaccess',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widget_access', to='client.Client'),
        ),
    ]
