# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-08-24 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0068_auto_20260812_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardwidgetvisibilityaccess',
            name='latest_audit_cycle_score',
        ),
        migrations.RemoveField(
            model_name='dashboardwidgetvisibilityaccess',
            name='overall_high_performance_city',
        ),
        migrations.RemoveField(
            model_name='dashboardwidgetvisibilityaccess',
            name='overall_high_performance_store',
        ),
        migrations.RemoveField(
            model_name='dashboardwidgetvisibilityaccess',
            name='overall_low_performance_city',
        ),
        migrations.RemoveField(
            model_name='dashboardwidgetvisibilityaccess',
            name='overall_low_performance_store',
        ),
        migrations.AddField(
            model_name='dashboardwidgetvisibilityaccess',
            name='city_wise_performance',
            field=models.BooleanField(db_column='city_wise_performance', default=True),
        ),
        migrations.AddField(
            model_name='dashboardwidgetvisibilityaccess',
            name='overall_audit_cycle_score',
            field=models.BooleanField(db_column='overall_audit_cycle_score', default=True),
        ),
        migrations.AddField(
            model_name='dashboardwidgetvisibilityaccess',
            name='store_wise_performance',
            field=models.BooleanField(db_column='store_wise_performance', default=True),
        ),
    ]
