update auditor_profileinfo set city = 'Bangalore' where city in ('Bangalore', 'bangalore','BANGALORE','Banglore','Bangalore``', 'banglore', 'Bangaluru', 'Bengaluru');
update auditor_profileinfo set city = 'Delhi' where city in ('New-delhi', 'delhi ncr','New  Delhi','DELHI','delhi', 'Delhi');
update auditor_profileinfo set city = 'Noida' where city in ('greater noida', 'Greater Noida','noida','NOIDA','Noida');
update auditor_profileinfo set city = 'Kochi' where city in ('cochin', 'Cochin','COCHIN','kochi','KOCHI');
update auditor_profileinfo set city = 'Kozhikode' where city in ('calicut', 'calicut');
update auditor_profileinfo set city = 'Vijayawada' where city in ('vijayawada', 'vijayawad');
update auditor_profileinfo set city = 'Thane' where city in ('Thane East', 'Thane Mumbai','Thane (W)');
update auditor_profileinfo set city = 'Alapuzha' where city in ('alapuzha');
update auditor_profileinfo set city = 'Visakhapatnam' where city in ('VISAKHPATNAM', 'VISHAKAPATNAM');
update auditor_profileinfo set city = 'Secunderabad' where city in ('secunderabad', 'SECUNDERABAD');
update auditor_profileinfo set city = 'Hyderabad' where city in ('hydrabad', 'HYDRABAD');
update auditor_profileinfo set city = 'Navi Mumbai' where city in ('NaviMumbai', 'Navi Mumbai 400703', 'new mumbai');
update auditor_profileinfo set city = 'Gurgaon' where city in ('Gugaon', 'Gurga', 'Gurgain');
update auditor_profileinfo set city = 'Mangalore' where city in ('MANGALURU');
update auditor_profileinfo set city = 'North Goa' where city in ('Goa', 'GOA');
update auditor_profileinfo set city = 'Goa North' where city in ('North Goa');
update auditor_profileinfo set city = 'Panjim' where city in ('panaji', 'Panaji');
update auditor_profileinfo set city = 'Guwahati' where city in ('guwhati');
update auditor_profileinfo set city = 'Nashik' where city in ('Nasik', 'NASIK');
update auditor_profileinfo set city = 'Kozhikode' where city in ('Calicut');
update auditor_profileinfo set city = 'Kolkata' where city in ('Kolkats');
update auditor_profileinfo set city = 'Nallasopara' where city in ('Nallasopara West');
update auditor_profileinfo set city = 'Ghaziabad' where city in ('gazyabad', 'GHAZIBAD');
update auditor_profileinfo set city = 'Indore' where city in ('Indoe');
update auditor_profileinfo set city = 'Delhi' where city in ('New dlehi');
update auditor_profileinfo set city = 'Jalandhar' where city in ('JALANDHAR CITY');
update auditor_profileinfo set city = 'Dindigul' where city in ('Dindigul Dt');
update auditor_profileinfo set city = 'Adipur' where city in ('adipur');
update auditor_profileinfo set city = 'Margao' where city in ('Margoa');
update auditor_profileinfo set city = 'Srerampore' where city in ('Rishra; Srerampore');
update auditor_profileinfo set city = 'Thrissur	' where city in ('Thrsisur');
update auditor_profileinfo set city = 'Tirupur	' where city in ('TIRUPPUR');
update auditor_profileinfo set city = 'Tambaram	' where city in ('tambaram west');
update auditor_profileinfo set city = 'Bangalore' where city in ('Electronic City');

insert into manager_city values(716, 'Palghar', 'IN-MH');
insert into manager_city values(717, 'Adipur', 'IN-GJ');
insert into manager_city values(718, 'Ramnagar', 'IN-UK');
