##
## Rename this file to properties.ini and fill in your values below
##

[GENERAL]
BASE_DOMAIN_NAME=localhost:8000
SECRET_KEY=super_secret
DEBUG=True

### IMGIX subdomain source configured to serve attachments
IMGIX_SUBDOMAIN=fw-att-test.imgix.net

[DATABASE]
ENGINE=django.db.backends.postgresql_psycopg2
NAME=db_name
USER=db_user
PASSWORD=db_pass
HOST=db_host
PORT=5432

[EMAIL_SETTINGS]
HOST=smtp.gmail.com
PORT=587
HOST_USER=foo@bar.com
HOST_PASSWORD=password
DEFAULT_FROM_EMAIL=Admin <admin@example.com>
SERVER_EMAIL=Admin <admin@foobar.com>

[PAYMENT_CSV_SETTINGS]
ORDERINGACCNO=2541109900110007
REMITTER_NAME=FLOORWALK CONSULTANTS PVT LTD
SENTTORECVINFO=Floorwalk Audit fees
INDICATOR=EML
ORIGINAL_REMITTER=FLOORWALK CONSULTANTS PVT LTD

[S3_ATTACHMENTS]
AWS_ACCESS_KEY_ID=foobar
AWS_SECRET_ACCESS_KEY=foobar_secret
BUCKET=fw-attachments-test
REGION=ap-southeast-1
MIN_SIZE=1024
### 20 * 1024 * 1024 = 20971520 bytes
MAX_SIZE=20971520
FILE_SLUG_SIZE=10

[LOGGER_SETTINGS]
### set log level to any one of: DEBUG, INFO, WARNING, ERROR, CRITICAL
### set to INFO preferably
LOG_LEVEL=INFO

### set this to the file where django logs are recorded
DJANGO_LOG_FILENAME=/home/foobar/logs/kronos/django.log

### add log handlers, can contain 'logfile' which logs to above file or 'console' or both
### should use only 'logfile' in production and only 'console' in development
LOG_HANDLERS=console,logfile

### add a switch for email sending email notifications
### when set to true, emails will be sent when the action is triggered
[EMAIL_SWITCH]
NOTIFICATION=False
VERIFICATION=False
PRE_REMINDER=False
ON_REMINDER=False
POST_REMINDER=False
WELCOME=False

[FRONTEND]
CLIENT_IMPACT_FACTOR_URL=https://s3-ap-southeast-1.amazonaws.com/bucket_name/object_path
CLIENT_TWEET_DATA_URL=https://s3-ap-southeast-1.amazonaws.com/bucket_name/object_path
AUDITOR_FB_CLIENT_ID=999999999999999
AUDITOR_FB_FIELDS=id,name,first_name,last_name,gender,age_range,email,picture,likes,friends,location,birthday,link,verified
AUDITOR_FB_SCOPE=email,public_profile,user_friends,user_likes,user_location,user_birthday

### Google Analytics Tracking ID for Authentication/Registration views only
### The actual app should use different tracking IDs for manager,auditor and client UIs
AUDITOR_GA_ID=UA-XXXXXXXX-X

### Tawk.to src for live chat with auditors
TAWK_TO_SRC=https://embed.tawk.to/foobar/default

[REFERRAL]
SIGNUP_AMOUNT = 10
AUDIT_AMOUNT = 100
MAX_AUDIT_REFERRALS = 3
