# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 16:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('has_car', models.NullBooleanField(db_column='has_car')),
                ('weekend_audit', models.NullBooleanField(db_column='weekend_audit')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('bank_name', models.CharField(blank=True, db_column='bank_name', max_length=40)),
                ('account_holder_name', models.CharField(blank=True, db_column='account_holder_name', max_length=40)),
                ('account_number', models.CharField(blank=True, db_column='account_number', max_length=20)),
                ('ifsc_code', models.CharField(blank=True, db_column='ifsc_code', max_length=20)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileInfo',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_column='first_name', max_length=20)),
                ('last_name', models.CharField(blank=True, db_column='last_name', max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], db_column='gender', max_length=1)),
                ('marital_status', models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], db_column='marital_status', max_length=1)),
                ('education', models.CharField(blank=True, choices=[('TE', '10th (Middle School)'), ('TW', '12th (High School)'), ('CO', 'In College'), ('GR', 'Graduate'), ('PG', 'Post Graduate and Above')], db_column='education', max_length=2)),
                ('mobile_number', models.CharField(blank=True, db_column='mobile_number', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, db_column='dob', null=True)),
                ('address', models.CharField(blank=True, db_column='address', max_length=100)),
                ('pincode', models.CharField(blank=True, db_column='pincode', max_length=8)),
                ('city', models.CharField(blank=True, db_column='city', max_length=20)),
                ('state', models.CharField(blank=True, db_column='state', max_length=20)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
