# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20161021_1102'),
        ('auditor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditApplication',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NOT_APPLIED', 'Not Applied'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected'), ('ASSIGNED', 'Assigned'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], db_column='status', max_length=20)),
                ('audit_date', models.DateField(db_column='audit_date')),
                ('auditlocation', models.ForeignKey(db_column='audit_location_id', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='manager.AuditLocation')),
                ('profileinfo', models.ForeignKey(db_column='profileinfo_id', on_delete=django.db.models.deletion.CASCADE, to='auditor.ProfileInfo')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='auditapplication',
            unique_together=set([('profileinfo', 'auditlocation')]),
        ),
    ]
