# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0002_auto_20161023_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditapplication',
            name='profileinfo',
            field=models.ForeignKey(db_column='profileinfo_id', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='auditor.ProfileInfo'),
        ),
    ]
