# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 06:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0003_auto_20161025_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinfo',
            name='account_number',
            field=models.CharField(blank=True, db_column='account_number', max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numberic values accepted')]),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='mobile_number',
            field=models.CharField(blank=True, db_column='mobile_number', max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numberic values accepted'), django.core.validators.MinLengthValidator(10, 'Field requires 10 characters')]),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='pincode',
            field=models.CharField(blank=True, db_column='pincode', max_length=8, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numberic values accepted')]),
        ),
    ]
