# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0004_auto_20161105_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='camera_owned',
            field=models.NullBooleanField(db_column='camera_owned'),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='camera_resoulution',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 to 5 megapixel'), (2, '5 to 10 megapixel'), (3, '10 to 15 megapixel'), (4, '15+ megapixel'), (5, 'dont know'), (6, 'no camera')], db_column='camera_resolution', null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='distance',
            field=models.PositiveSmallIntegerField(blank=True, db_column='distance', null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='ethnicity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'african american'), (2, 'asian'), (3, 'caucasian'), (4, 'hispanic'), (5, 'middle eastern'), (6, 'native american'), (7, 'other')], db_column='ethnicity', null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='fax_access',
            field=models.NullBooleanField(db_column='fax_access'),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='hair_color',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'black'), (2, 'blonde'), (3, 'brown'), (4, 'red'), (5, 'grey'), (6, 'white'), (7, 'bald'), (8, 'other')], db_column='hair_color', null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, db_column='height', null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='laptop_owned',
            field=models.NullBooleanField(db_column='laptop_owned'),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='pda_owned',
            field=models.NullBooleanField(db_column='pda_owned'),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='scanner_access',
            field=models.NullBooleanField(db_column='scanner_access'),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='smart_phone_owned',
            field=models.NullBooleanField(db_column='smart_phone_owned'),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, db_column='weight', null=True),
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='pan_number',
            field=models.CharField(blank=True, db_column='pan_number', max_length=10),
        ),
    ]
