# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0005_auto_20161110_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='household_income',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'not answered'), (1, 'less than 1\t\t lpa'), (2, '1 to 3 lpa'), (3, '3 to 8 lpa'), (4, '8 to 15 lpa'), (5, '15+ lpa')], db_column='household_income', null=True),
        ),
    ]
