# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0006_profileinfo_household_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinfo',
            name='bank_address',
            field=models.CharField(blank=True, db_column='bank_address', max_length=100),
        ),
    ]
