# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 19:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0008_auto_20161112_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinfo',
            name='pan_number',
            field=models.CharField(blank=True, db_column='pan_number', max_length=10),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='mobile_number',
            field=models.CharField(blank=True, db_column='mobile_number', max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numberic values accepted'), django.core.validators.MinLengthValidator(10, 'Field requires 10 characters')]),
        ),
    ]
