# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0009_auto_20161112_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinfo',
            name='bank_address',
            field=models.CharField(blank=True, db_column='bank_address', max_length=300),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='address',
            field=models.CharField(blank=True, db_column='address', max_length=300),
        ),
    ]
