# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0010_auto_20161112_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinfo',
            name='pan_number',
            field=models.CharField(blank=True, db_column='pan_number', max_length=15),
        ),
    ]
