# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 19:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0011_auto_20161112_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinfo',
            name='account_number',
            field=models.CharField(blank=True, db_column='account_number', max_length=40, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numberic values accepted')]),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='city',
            field=models.CharField(blank=True, db_column='city', max_length=40),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='first_name',
            field=models.CharField(blank=True, db_column='first_name', max_length=40),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='last_name',
            field=models.CharField(blank=True, db_column='last_name', max_length=40),
        ),
    ]
