# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0012_auto_20161112_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinfo',
            name='ifsc_code',
            field=models.CharField(blank=True, db_column='ifsc_code', max_length=40),
        ),
    ]
