# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_audit_earnings_per_audit'),
        ('auditor', '0015_auto_20161117_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='city_id',
            field=models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.City'),
        ),
    ]
