# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 11:35
from __future__ import unicode_literals

from django.db import migrations

#from manager.models import City

def add_city_id(apps, schema_editor):
    ProfileInfo = apps.get_model('auditor', 'ProfileInfo')
    City = apps.get_model('manager', 'City')
    mancities = City.objects.all()
    for pi in ProfileInfo.objects.all():
        for mancity in mancities:
            if (str.lower(mancity.name.replace(" ", "")) == str.lower(pi.city.replace(" ", ""))):
                pi.city_id = mancity
                pi.save()

class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0016_profileinfo_city_id'),
    ]

    operations = [
        migrations.RunPython(add_city_id)
    ]
