# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0017_add_city_id'),
    ]

    operations = [
        migrations.RenameField('profileinfo', 'city', 'city_name'),
        migrations.AlterField(
            model_name='profileinfo',
            name='city_name',
            field=models.CharField(blank=True, db_column='city_name', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='city_id',
            field=models.ForeignKey(blank=True, db_column='city', null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.City'),
        ),
        migrations.RenameField('profileinfo', 'city_id', 'city'),
    ]
