# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0018_auto_20170124_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='city',
            field=models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.City'),
        ),
    ]
