# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('auditor', '0019_auto_20170125_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditapplication',
            name='audit',
            field=models.ForeignKey(db_column='audit_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='audit.Audit'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='auditapplication',
            unique_together=set([('profileinfo', 'audit')]),
        ),
        migrations.RemoveField(
            model_name='auditapplication',
            name='auditlocation',
        ),
    ]
