# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-28 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0020_auto_20170126_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditapplication',
            name='status',
            field=models.CharField(choices=[('NOT_APPLIED', 'Not Applied'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved')], db_column='status', max_length=20),
        ),
    ]
