# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0022_auto_20170209_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='occupation',
            field=models.CharField(blank=True, choices=[('STUDENT', 'student'), ('SERVICE', 'service'), ('SELF_EMPLOYED', 'self employed'), ('BUSINESS', 'business'), ('UNEMPLOYED', 'unemployed'), ('RETIRED', 'retired')], db_column='occupation', max_length=20, null=True),
        ),
    ]
