# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0023_additionalinfo_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfo',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='state',
        ),
    ]
