# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 19:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0024_auto_20170313_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='mobile_number',
            field=models.CharField(blank=True, db_column='mobile_number', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numberic values accepted'), django.core.validators.MinLengthValidator(10, 'Field requires 10 characters')]),
        ),
    ]
