# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0027_auto_20170426_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='car_cost',
            field=models.PositiveIntegerField(blank=True, db_column='car_cost', null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='car_model',
            field=models.CharField(blank=True, db_column='car_model', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='company',
            field=models.CharField(blank=True, db_column='company', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='industry',
            field=models.CharField(blank=True, db_column='industry', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='laptop_model',
            field=models.CharField(blank=True, db_column='laptop_model', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='mobile_model',
            field=models.CharField(blank=True, db_column='mobile_model', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='mspa_code',
            field=models.CharField(blank=True, db_column='mspa_code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='referral_code',
            field=models.CharField(blank=True, db_column='referral_code', max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='referred_by',
            field=models.CharField(blank=True, db_column='referred_by', max_length=10, null=True),
        ),
    ]
