# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0028_auto_20170707_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditapplication',
            name='audit',
            field=models.ForeignKey(db_column='audit_id', on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='audit.Audit'),
        ),
        migrations.AlterField(
            model_name='auditapplication',
            name='profileinfo',
            field=models.ForeignKey(db_column='profileinfo_id', on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='auditor.ProfileInfo'),
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='city',
            field=models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.City'),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
