# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-16 08:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auditor', '0030_auto_20171010_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('receive_new_opportunities_email', models.BooleanField(db_column='receive_new_opportunities_email', default=True)),
                ('receive_transactional_email', models.BooleanField(db_column='receive_transactional_email', default=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
