# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-08 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0031_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditapplication',
            name='status',
            field=models.CharField(choices=[('NOT_APPLIED', 'Not Applied'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Wait Listed'), ('APPROVED', 'Approved')], db_column='status', max_length=20),
        ),
    ]
