# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-02 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0032_auto_20180108_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='agreement_accepted',
            field=models.BooleanField(db_column='agreement_accepted', default=False),
        ),
        migrations.AddField(
            model_name='preferences',
            name='pp_accepted',
            field=models.BooleanField(db_column='pp_accepted', default=False),
        ),
    ]
