# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-15 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0033_auto_20180202_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='receive_new_opportunities_sms',
            field=models.BooleanField(db_column='receive_new_opportunities_sms', default=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='receive_transactional_sms',
            field=models.BooleanField(db_column='receive_transactional_sms', default=True),
        ),
    ]
