# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0034_auto_20180215_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditapplication',
            name='report_exists',
            field=models.BooleanField(db_column='report_exists', default=False),
        ),
    ]
