# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-24 08:45
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auditor', '0035_auditapplication_report_exists'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNumberHistoryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, db_column='mobile_number', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric values accepted'), django.core.validators.MinLengthValidator(10, 'Field requires 10 characters')])),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
