# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-28 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0037_auto_20200324_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditapplication',
            name='status',
            field=models.CharField(choices=[('NOT_APPLIED', 'Not Applied'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('WAITLISTED', 'Wait Listed'), ('APPROVED', 'Approved')], db_column='status', max_length=20),
        ),
    ]
