# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-29 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0038_auto_20200328_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='auditor_rating',
            field=models.CharField(choices=[('E', 'Excellent'), ('G', 'Good'), ('A', 'Average'), ('W', 'Worse')], db_column='auditor_rating', max_length=1, null=True),
        ),
    ]
