# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-08-18 09:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0039_profileinfo_auditor_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditapplication',
            name='report_exists_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_column='report_exists_data', default=dict),
        ),
    ]
