# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-08-31 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0040_auditapplication_report_exists_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='income',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'not answered'), (1, 'less than 1\t\t lpa'), (2, '1 to 3 lpa'), (3, '3 to 8 lpa'), (4, '8 to 15 lpa'), (5, '15+ lpa')], db_column='income', null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='pronouns',
            field=models.CharField(blank=True, db_column='pronouns', max_length=40),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='car_cost',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '<3 lacs'), (2, '3 lacs – 5 lacs'), (3, '5 lacs – 10 lacs'), (4, '10 lacs – 15 lacs'), (5, '15 lacs and above')], db_column='car_cost', null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='industry',
            field=models.CharField(blank=True, choices=[(1, 'Advertising and Marketing'), (2, 'Agriculture'), (3, 'Arts'), (4, 'Architecture'), (5, 'Advisory'), (6, 'Accounting'), (7, 'Aviation'), (8, 'Apprael'), (9, 'Automotive'), (10, 'Banking'), (11, 'Biotechnology'), (12, 'Civil Engineering'), (13, 'Civic-Social organization'), (14, 'Consumer Goods and Services'), (15, 'Cosmetics'), (16, 'Entertainment'), (17, 'Event Management'), (18, 'Financial Services'), (19, 'Food and Beverage'), (20, 'Graphic Designing'), (21, 'Health and Fitnes'), (22, 'Hospitality'), (23, 'Import-Export Industry'), (24, 'Information Technology'), (25, 'Insurance'), (26, 'Luxury Goods'), (27, 'Management Consulting'), (28, 'Market Research'), (29, 'Medical'), (30, 'Music'), (31, 'Not for Profit'), (32, 'Oil and Energy'), (33, 'Pharmaceuticals'), (34, 'Photography'), (35, 'Real-Estate'), (36, 'Retail Industry'), (37, 'Sales'), (38, 'Sports'), (39, 'Supply Chain and Logistics'), (40, 'Telecommunications'), (41, 'Transportation'), (42, 'Veterinary'), (43, 'Other')], db_column='industry', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Trans person'), ('N', 'Non-binary')], db_column='gender', max_length=1),
        ),
    ]
