# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-24 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0042_auto_20210831_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='full_time_opportunity_email_status',
            field=models.BooleanField(db_column='full_time_opportunity_email_status', default=False),
        ),
    ]
