# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-29 08:16
from __future__ import unicode_literals

from django.db import migrations, models

def gen_beneficiary_id(apps, schema_editor):
    BankInfo = apps.get_model('auditor', 'BankInfo')
    for bank in BankInfo.objects.all():
        bank.beneficiary_id = "BEN0{}".format(bank.user.id)
        bank.save()

class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0043_preferences_full_time_opportunity_email_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinfo',
            name='beneficiary_checked',
            field=models.BooleanField(db_column='beneficiary_checked', default=False),
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='beneficiary_id',
            field=models.CharField(db_column='beneficiary_id', max_length=100, null=True),
        ),
    ]
