# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-10 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0044_auto_20210929_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankinfo',
            name='beneficiary_checked',
        ),
        migrations.RemoveField(
            model_name='bankinfo',
            name='beneficiary_id',
        ),
    ]
