# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-12-16 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0045_auto_20211010_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='is_tour_complete',
            field=models.BooleanField(db_column='is_tour_complete', default=False),
        ),
    ]
