# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-12-20 08:20
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0046_additionalinfo_is_tour_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='interest_area',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, db_column='interest_area', null=True, size=None),
        ),
    ]
