# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-12-28 09:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0047_additionalinfo_interest_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='whatsapp_number',
            field=models.CharField(blank=True, db_column='whatsapp_number', max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric values accepted'), django.core.validators.MinLengthValidator(10, 'Field requires 10 characters')]),
        ),
    ]
