# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-12-28 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0048_profileinfo_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='receive_transactional_whatsapp_message',
            field=models.BooleanField(db_column='receive_transactional_whatsapp_message', default=True),
        ),
    ]
