# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-02-10 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0050_whatsappnumberhistorylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditapplication',
            name='comment',
            field=models.CharField(blank=True, db_column='comment', max_length=1000, null=True),
        ),
    ]
