# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-04-18 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0052_auditorrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='is_super_auditor',
            field=models.BooleanField(db_column='is_super_auditor', default=False),
        ),
    ]
