# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-05-10 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0053_profileinfo_is_super_auditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='certification_score',
            field=models.PositiveSmallIntegerField(db_column='certification_score', null=True),
        ),
    ]
