# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-08-23 09:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0054_profileinfo_certification_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='language_known',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, db_column='language_known', null=True, size=None),
        ),
    ]
