# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-09-27 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0055_additionalinfo_language_known'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditapplication',
            name='auto_approve',
            field=models.BooleanField(db_column='auto_approve', default=False),
        ),
    ]
