# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-09-28 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0056_auditapplication_auto_approve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditapplication',
            name='auto_approve',
        ),
        migrations.AddField(
            model_name='auditapplication',
            name='is_automation_approve',
            field=models.BooleanField(db_column='is_automation_approve', default=False),
        ),
    ]
