# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-10-03 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0057_auto_20230928_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditapplication',
            name='is_instant_approve',
            field=models.BooleanField(db_column='is_instant_approve', default=False),
        ),
    ]
