# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-10-04 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0058_auditapplication_is_instant_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditapplication',
            name='apply_count',
            field=models.PositiveSmallIntegerField(db_column='apply_count', default=0),
        ),
    ]
