# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-04-08 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0059_auditapplication_apply_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinfo',
            name='paypal',
            field=models.CharField(blank=True, db_column='paypal', max_length=30, null=True),
        ),
    ]
