# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-05-30 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0061_auto_20240530_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='dial_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
