# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-05-30 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0062_profileinfo_dial_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileinfo',
            old_name='dial_code',
            new_name='dail_code',
        ),
    ]
