# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-05-30 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0064_auto_20240530_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='whatsapp_dial_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='income',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'not answered'), (1, 'less than 1200 $\t'), (2, '1200 $ to 3600 lpa'), (3, '3600 $ to 9600 lpa'), (4, '9600 $ to 18000 $'), (5, '18000 $ to 50000 $'), (5, '50000 $ + pa')], db_column='income', null=True),
        ),
    ]
