# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-05-30 12:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0066_auto_20240530_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilenumberhistorylog',
            name='mobile_number',
            field=models.CharField(blank=True, db_column='mobile_number', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric values accepted'), django.core.validators.MinLengthValidator(10, 'Field requires 10 characters')]),
        ),
        migrations.AlterField(
            model_name='whatsappnumberhistorylog',
            name='whatsapp_number',
            field=models.CharField(blank=True, db_column='whatsapp_number', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric values accepted'), django.core.validators.MinLengthValidator(10, 'Field requires 10 characters')]),
        ),
    ]
