# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-06-12 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0067_auto_20240530_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='car_cost',
            field=models.CharField(blank=True, choices=[('', ''), (1, '<3600 $'), (2, '3600 $ – 6000 $'), (3, '6000 $ – 12000 $'), (4, '12000 $ – 18000 $'), (5, '18000 $ and above')], db_column='car_cost', max_length=50, null=True),
        ),
    ]
