# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-09-22 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0068_auto_20240612_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='designation',
            field=models.CharField(blank=True, db_column='designation', max_length=50, null=True),
        ),
    ]
