# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-09-22 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0069_additionalinfo_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='household_income',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'not answered'), (1, 'upto 5\t\t lpa'), (2, '5 to 10 lpa'), (3, '10 to 15 lpa'), (4, '15 to 25 lpa'), (5, '25 to 50 lpa'), (5, '50 l to 1 cr'), (6, '1+ cr')], db_column='household_income', null=True),
        ),
    ]
