# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-10-08 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0071_auto_20250922_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='created_at',
            field=models.DateTimeField(db_column='created_at', null=True),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='modified_at',
            field=models.DateTimeField(db_column='modified_at', null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='created_at',
            field=models.DateTimeField(db_column='created_at', null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='modified_at',
            field=models.DateTimeField(db_column='modified_at', null=True),
        ),
    ]
