# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-04-14 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0072_auto_20251008_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorAppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10, unique=True)),
                ('latest_version', models.CharField(blank=True, db_column='latest_version', max_length=20, null=True)),
                ('min_supported_version', models.CharField(blank=True, db_column='min_supported_version', max_length=20, null=True)),
                ('force_update', models.BooleanField(db_column='force_update', default=False)),
                ('update_message', models.TextField(blank=True, db_column='update_message', null=True)),
                ('store_url', models.CharField(blank=True, db_column='store_url', max_length=500, null=True)),
                ('app_enabled', models.BooleanField(db_column='app_enabled', default=True)),
            ],
        ),
    ]
