# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 08:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_store', '0005_auto_20170205_1451'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('comment', models.CharField(db_column='comment', max_length=500)),
                ('amount', models.IntegerField(db_column='amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], db_column='status', default='PENDING', max_length=20)),
                ('added_on', models.DateTimeField(auto_now_add=True, db_column='added_on')),
                ('paid_on', models.DateTimeField(db_column='paid_on', null=True)),
                ('audit_store', models.OneToOneField(db_column='audit_store_id', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='audit_store.AuditStore')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
