# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 18:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit_store', '0005_auto_20170205_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, db_column='comment', max_length=500)),
                ('amount', models.IntegerField(db_column='amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], db_column='status', max_length=20)),
                ('deleted', models.BooleanField(db_column='deleted', default=False)),
                ('audit_store_id', models.ForeignKey(db_column='audit_store_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='audit_store.AuditStore')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
