# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20170614_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='audit_store',
            field=models.OneToOneField(db_column='audit_store_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='audit_store.AuditStore'),
        ),
    ]
