# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-16 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20170614_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='deleted',
        ),
        migrations.AddField(
            model_name='payment',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, db_column='added_on', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_on',
            field=models.DateTimeField(db_column='paid_on', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='audit_store',
            field=models.OneToOneField(db_column='audit_store_id', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='audit_store.AuditStore'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='comment',
            field=models.CharField(db_column='comment', max_length=500),
        ),
    ]
