# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-25 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20171128_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='audit_store',
            field=models.ForeignKey(db_column='audit_store_id', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='audit_store.AuditStore'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], db_column='status', default='PENDING', max_length=20),
        ),
    ]
