# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-10 05:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0004_auto_20180325_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('beneficiary_id', models.CharField(db_column='beneficiary_id', editable=False, max_length=100, unique=True)),
                ('beneficiary_checked', models.BooleanField(db_column='beneficiary_checked', default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
