from django.conf.urls import url
from . import views

urlpatterns = ([
    url(r'report/audit_cycle/(?P<audit_cycle_id>[0-9]+)/city/(?P<city_id>[0-9]+)/store$', views.AuditCycleCityStoreAverageReport.as_view(), name='audit_cycle_city_store_average'),
    url(r'report/audit_cycle/(?P<audit_cycle_id>[0-9]+)/store/(?P<store_id>[0-9]+)$', views.AuditCycleStoreSectionAverageReport.as_view(), name='audit_cycle_store_section_average'),
    url(r'report/audit_cycle/(?P<audit_cycle_id>[0-9]+)/store/(?P<store_id>[0-9]+)/audit_store$', views.AuditCycleAuditStoreSectionReport.as_view(), name='audit_cycle_audit_store_section'),
    url(r'report/audit_cycle/(?P<audit_cycle_id>[0-9]+)/city/(?P<city_id>[0-9]+)$', views.AuditCycleCitySectionAverageReport.as_view(), name='audit_cycle_city_section_average'),
    url(r'report/audit_cycle/(?P<audit_cycle_id>[0-9]+)/audit_store$', views.AuditStoreView.as_view(), name='audit_store_view'),
    url(r'report/audit_cycle/(?P<audit_cycle_id>[0-9]+)$', views.AuditCycleCityAverageReport.as_view(), name='audit_cycle_city_average'),
    url(r'report/audit_cycle/(?P<audit_cycle_id>[0-9]+)/performance/city$', views.AuditCycleCityPerformance.as_view(), name='audit_cycle_city_performance'),
    url(r'report/audit_cycle/(?P<audit_cycle_id>[0-9]+)/performance/store$', views.AuditCycleStorePerformance.as_view(), name='audit_cycle_store_performance'),
    url(r'report/performance/store$', views.DashboardStoreTrends.as_view(), name='dashboard_store_trends'),
    url(r'report/performance/city$', views.DashboardCityWiseTrends.as_view(), name='dashboard_city_trends'),
    url(r'report/performance/store_xlsx$', views.DashboardStoreTrendsXlsx.as_view(), name='dashboard_store_trends_xlsx'),
    url(r'report/performance/city_xlsx$', views.DashboardCityWiseTrendsXlsx.as_view(), name='dashboard_city_trends_xlsx'),
    url(r'report/audit_cycle/(?P<audit_cycle_id>[0-9]+)/city$', views.AuditCycleCityPerformance.as_view(), name='audit_cycle_city_performance'),
    url(r'report/audit_cycle/time_series$', views.AuditCycleTimeSeriesReport.as_view(), name='audit_cycle_time_series'),
    url(r'report/audit_cycle/time_series_xlsx$', views.AuditCycleTimeSeriesReportXlsx.as_view(), name='audit_cycle_time_series_xlsx'),
    url(r'report/store/(?P<store_id>[0-9]+)/marking', views.MarkingByStore.as_view(), name='marking_by_store'),
    url(r'audit_cycle/(?P<audit_cycle_id>[0-9]+)/audit_cycle_xlsx_report$', views.AuditCycleXlsxReport.as_view(), name='audit_cycle_xlsx_report'),
    url(r'audit_cycle/(?P<audit_cycle_id>[0-9]+)/audit_cycle_filtered_xlsx_report$', views.AuditCycleFilteredXlsxReport.as_view(), name='audit_cycle_filtered_xlsx_report'),

    url(r'audit_store/latest$', views.AuditStoreLatest.as_view(), name='audit_store_latest'),
    url(r'audit_store/(?P<audit_store_id>[0-9]+)/attachment$', views.AttachmentByAuditStore.as_view(), name='attachment_by_audit_store'),
    url(r'audit_store/(?P<audit_store_id>[0-9]+)/answer$', views.AnswerByAuditStore.as_view(), name='answer_by_audit_store'),
    url(r'audit_store/(?P<audit_store_id>[0-9]+)/section$', views.SectionByAuditStore.as_view(), name='section_by_audit_store'),
    url(r'audit_store/(?P<audit_store_id>[0-9]+)/section/(?P<section_id>[0-9]+)/attachment$', views.AttachmentByReportSection.as_view(), name='attachment_by_report_section'),
    url(r'audit_store/(?P<audit_store_id>[0-9]+)/report_section$', views.ReportSectionByAuditStore.as_view(), name='report_section_by_audit_store'),
    url(r'audit_store/(?P<audit_store_id>[0-9]+)/xlsx_report$', views.AuditStoreXlsxReport.as_view(), name='audit_store_xlsx_report'),
    url(r'audit_store/(?P<audit_store_id>[0-9]+)/ears_report$', views.AuditStoreEARSReport.as_view(), name='audit_store_ears_report'),
    url(r'audit_store/upcoming$', views.AuditStoreUpcoming.as_view(), name='audit_store_upcoming'),
    url(r'audit_store/(?P<audit_store_id>[0-9]+)$', views.AuditStoreIdView.as_view(), name='audit_store_id_view'),
    url(r'store/(?P<store_id>[0-9]+)/audit_store$', views.AuditStoreByStore.as_view(), name='audit_store_by_store'),
    url(r'store/(?P<store_id>[0-9]+)$', views.StoreById.as_view(), name='store_by_id'),
    url(r'store$', views.StoreByClient.as_view(), name='store_by_client'),
    url(r'user$', views.ClientUserView.as_view(), name='client_user_view'),
    url(r'audit_cycle$', views.AuditCycleView.as_view(), name='audit_cycle_view'),
    url(r'audit_cycle/(?P<audit_type>[A-Z_]+)$', views.AuditCycleByTypeView.as_view(), name='audit_cycle_by_type_view'),
    url(r'audit_cycle/aggregation$', views.AuditCycleAggregate.as_view(), name='audit_cycle_aggregation'),
    url(r'types$', views.AuditTypesByClient.as_view(), name='audit_types_by_client'),
    url(r'city$', views.CityView.as_view(), name='city_view'),
    url(r'config$', views.ConfigView.as_view(), name='config_view'),
    url(r'twitter/handles/(?P<twitter_handle_id>[0-9]+)/feed$', views.TwitterFeedView.as_view(), name='twitter_feed_view'),
    url(r'twitter/handles', views.TwitterHandlesView.as_view(), name='twitter_handles_view'),
], 'client_rest')
