var types = {
	/*Profile Info Action Types*/
	PROFILE_INFO_GET: 'PROFILE_INFO_GET',
	PROFILE_INFO_POST: 'PROFILE_INFO_POST',

	/*Bank Info Action Types*/
	BANK_INFO_GET: 'BANK_INFO_GET',
	BANK_INFO_POST: 'BANK_INFO_POST',

	/*Additional Info Action Types*/
	ADDITIONAL_INFO_GET: 'ADDITIONAL_INFO_GET',
	ADDITIONAL_INFO_POST: 'ADDITIONAL_INFO_POST',

	AUDIT_GET: 'AUDIT_GET',
	AUDIT_ID_GET: 'AUDIT_ID_GET',

	APPLICATION_GET: 'APPLICATION_GET',

	AUDIT_APPLY_FORM_LOAD: 'AUDIT_APPLY_FORM_LOAD',
	AUDIT_APPLY_FORM_SUB: 'AUDIT_APPLY_FORM_SUB',

	AUDIT_CANCEL_FORM_LOAD: 'AUDIT_CANCEL_FORM_LOAD',
	AUDIT_CANCEL_FORM_SUB: 'AUDIT_CANCEL_FORM_SUB',

	AUDIT_STORE_GET: 'AUDIT_STORE_GET',
	AUDIT_STORE_ID_GET: 'AUDIT_STORE_ID_GET',

	SECTION_GET: 'SECTION_GET',

	ANSWER_GET: 'ANSWER_GET',
	ANSWER_POST: 'ANSWER_POST',

	//State get
	STATE_GET: 'STATE_GET',
	//City get
	CITY_GET: 'CITY_GET',
};

export default types;
