var types = {
	/*Profile Info Action Types*/
	PROFILE_INFO_GET_REQ: 'PROFILE_INFO_REQ',
	PROFILE_INFO_GET_ERR: 'PROFILE_INFO_ERR',
	PROFILE_INFO_GET_SUC: 'PROFILE_INFO_SUC',

	PROFILE_INFO_POST_REQ: 'PROFILE_INFO_POST_REQ',
	PROFILE_INFO_POST_ERR: 'PROFILE_INFO_POST_ERR',
	PROFILE_INFO_POST_SUC: 'PROFILE_INFO_POST_SUC',

	/*Bank Info Action Types*/
	BANK_INFO_GET_REQ: 'BANK_INFO_GET_REQ',
	BANK_INFO_GET_ERR: 'BANK_INFO_GET_ERR',
	BANK_INFO_GET_SUC: 'BANK_INFO_GET_SUC',

	BANK_INFO_POST_REQ: 'BANK_INFO_POST_REQ',
	BANK_INFO_POST_ERR: 'BANK_INFO_POST_ERR',
	BANK_INFO_POST_SUC: 'BANK_INFO_POST_SUC',

	/*Additional Info Action Types*/
	ADDITIONAL_INFO_GET_REQ: 'ADDITIONAL_INFO_GET_REQ',
	ADDITIONAL_INFO_GET_ERR: 'ADDITIONAL_INFO_GET_ERR',
	ADDITIONAL_INFO_GET_SUC: 'ADDITIONAL_INFO_GET_SUC',

	ADDITIONAL_INFO_POST_REQ: 'ADDITIONAL_INFO_POST_REQ',
	ADDITIONAL_INFO_POST_ERR: 'ADDITIONAL_INFO_POST_ERR',
	ADDITIONAL_INFO_POST_SUC: 'ADDITIONAL_INFO_POST_SUC',

	AUDIT_GET: 'AUDIT_GET',
	AUDIT_ID_GET: 'AUDIT_ID_GET',

	APPLICATION_GET: 'APPLICATION_GET',

	AUDIT_APPLY_FORM_LOAD: 'AUDIT_APPLY_FORM_LOAD',
	AUDIT_APPLY_FORM_SUB: 'AUDIT_APPLY_FORM_SUB',

	AUDIT_CANCEL_FORM_LOAD: 'AUDIT_CANCEL_FORM_LOAD',
	AUDIT_CANCEL_FORM_SUB: 'AUDIT_CANCEL_FORM_SUB',

	//State get
	STATE_GET: 'STATE_GET',
	//City get
	CITY_GET: 'CITY_GET',
};

export default types;
