# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('question_txt', models.CharField(db_column='question_txt', max_length=1024)),
                ('max_marks', models.PositiveIntegerField(db_column='max_marks')),
                ('sequence', models.PositiveIntegerField(db_column='sequence')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('sequence', models.PositiveIntegerField(db_column='sequence')),
                ('audit', models.ForeignKey(db_column='audit_cycle_id', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='audit.AuditCycle')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaire.Section'),
        ),
    ]
