# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='audit',
            new_name='audit_cycle',
        ),
    ]
