# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20170128_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['sequence']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['sequence']},
        ),
    ]
