# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 08:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20170203_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_column='question_data', default={}),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('PLAIN', 'Plain'), ('MUTEX', 'Mutually Exclusive')], db_column='question_type', default='PLAIN', max_length=20),
        ),
    ]
