# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20170810_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='questionnaire.Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='audit_cycle',
            field=models.ForeignKey(db_column='audit_cycle_id', on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='audit.AuditCycle'),
        ),
    ]
