# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_auto_20180109_1754'),
        ('questionnaire', '0005_auto_20170829_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireType',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=500)),
                ('is_default', models.BooleanField(db_column='is_default', default=False)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='questionnaire_types', to='client.Client')),
            ],
        ),
    ]
