# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20181020_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='minimum_attachment_count',
            field=models.IntegerField(db_column='minimum_attachment_count', default=0),
        ),
    ]
