# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-24 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0026_auditcycleprooftaglist'),
        ('questionnaire', '0008_section_minimum_attachment_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionProofTag',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_column='created_at', null=True)),
                ('audit_cycle_proof_tag', models.OneToOneField(db_column='audit_cycle_proof_tag_id', on_delete=django.db.models.deletion.PROTECT, related_name='section_proof_tag', to='audit.AuditCycleProofTagList')),
                ('section', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.PROTECT, related_name='section_proof_tag', to='questionnaire.Section')),
            ],
        ),
    ]
