# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-08-18 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_sectionprooftag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('PLAIN', 'Plain'), ('MUTEX', 'Mutually Exclusive'), ('MULTISELECT', 'Multiple Select')], db_column='question_type', default='PLAIN', max_length=20),
        ),
    ]
