# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-22 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_auto_20210818_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionprooftag',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
