# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-04-21 10:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_sectionprooftag_is_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemStatement',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=500)),
                ('industry', models.ForeignKey(db_column='industry_id', on_delete=django.db.models.deletion.PROTECT, related_name='problem_statements', to='questionnaire.Industry')),
            ],
        ),
        migrations.CreateModel(
            name='SampleQuestionnaire',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('questionnaire_data', django.contrib.postgres.fields.jsonb.JSONField(db_column='questionnaire_data', default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SampleQuestionnaireType',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=500)),
                ('problem_statement', models.ForeignKey(db_column='problem_statement_id', on_delete=django.db.models.deletion.PROTECT, related_name='questionnaire_types', to='questionnaire.ProblemStatement')),
            ],
        ),
        migrations.AddField(
            model_name='samplequestionnaire',
            name='sample_questionnaire_type',
            field=models.OneToOneField(db_column='sample_questionnaire_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='sample_questionnaire', to='questionnaire.SampleQuestionnaireType'),
        ),
    ]
