# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-05-02 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_auto_20220421_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='hide_comment',
            field=models.BooleanField(db_column='hide_comment', default=False),
        ),
    ]
