# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-06-01 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_section_hide_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hide_question',
            field=models.BooleanField(db_column='hide_question', default=False),
        ),
    ]
