# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-07-15 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0014_question_hide_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='base_rate',
            field=models.IntegerField(db_column='base_rate', default=0),
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='markup',
            field=models.IntegerField(db_column='markup', default=0),
        ),
        migrations.AddField(
            model_name='samplequestionnairetype',
            name='markup',
            field=models.IntegerField(db_column='markup', default=0),
        ),
    ]
