# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-07-27 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0015_auto_20220715_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='optional_comment_required',
            field=models.BooleanField(db_column='optional_comment_required', default=False),
        ),
    ]
