# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-07-29 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0016_question_optional_comment_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionprooftag',
            name='max_attachment_count',
            field=models.IntegerField(db_column='max_attachment_count', default=2),
        ),
    ]
