# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-02-09 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0017_sectionprooftag_max_attachment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('PLAIN', 'Plain'), ('MUTEX', 'Mutually Exclusive'), ('MULTISELECT', 'Multiple Select'), ('DATE', 'Date'), ('TIME', 'Time')], db_column='question_type', default='PLAIN', max_length=20),
        ),
    ]
