# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-06-23 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0018_auto_20260209_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_note',
            field=models.CharField(blank=True, db_column='question_note', max_length=520, null=True),
        ),
    ]
