# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-06-26 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0019_question_question_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(db_column='is_required', default=False),
        ),
    ]
