# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-07-08 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0020_question_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='visibility',
            field=models.CharField(choices=[('VISIBLE_TO_ALL', 'Visible to all'), ('HIDE_FROM_SHOPPER_AND_CLIENT', 'Hide from shoppers & clients'), ('HIDE_FROM_CLIENT', 'Hide from clients')], db_column='visibility', default='VISIBLE_TO_ALL', max_length=50),
        ),
    ]
