# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-08-17 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0021_question_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionprooftag',
            name='hide_from_client',
            field=models.BooleanField(db_column='visibility', default=False),
        ),
        migrations.AddField(
            model_name='sectionprooftag',
            name='is_comment_required',
            field=models.BooleanField(db_column='is_comment_required', default=False),
        ),
    ]
