# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-08-19 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0022_auto_20260817_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionprooftag',
            name='hide_from_client',
            field=models.BooleanField(db_column='hide_from_client', default=False),
        ),
    ]
