# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  package:
    docker:
      - image: datagovsg/python-node:3.6-6.10.3

    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-frontend-dependencies-{{ checksum "frontend/package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-frontend-dependencies-

      - run:
          name: install the frontend dependencies
          command: |
            cd frontend
            npm install

      - run:
          name: generate frontend bundles through webpack
          command: |
            cd frontend
            npm run build-prod

      - save_cache:
          paths:
            - ./frontend/node_modules
          key: v1-frontend-dependencies-{{ checksum "frontend/package-lock.json" }}

      - run:
          name: package the tar
          command: python setup.py sdist

      - store_artifacts:
          path: dist

  test:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_DB=kronos_db_test
      
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: write test properties
          command: cp .circleci/properties.test.ini properties.ini

      - run:
          name: create test results directory
          command: mkdir test-results

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test --verbosity=2 --with-xunit --xunit-file=test-results/xunittest.xml

      - store_artifacts:
          path: dist

      - store_artifacts:
          path: /tmp/kronos.log
          
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - package:
          requires:
            - test
