##
## Rename this file to properties.ini and fill in your values below
##

[GENERAL]
BRAND_NAME=FloorWalk Consultants Pvt. Ltd.
BRAND_SHORTNAME=FloorWalk
KRONOS_DOMAIN=localhost:8000
KRONOS_PROTOCOL=http
SECRET_KEY=super_secret
DEBUG=True
DEBUG_TOOLBAR=True
STATIC_ROOT=/home/ubuntu/kronos/
WHITENOISE_ENABLED=False

### IMGIX subdomain source configured to serve attachments
IMGIX_SUBDOMAIN=fw-att-test.imgix.net
THUMBOR_SUBDOMAIN=images.floorwalk.in

### SENTRY DSN for RAVEN Django plugin
SENTRY_DSN=https://68a03ad318ef45cc8e5f3dbc12f8f405:ceb4851469bf49e0ac9332ece3c8fab4@sentry.io/288151

### Audio Transcription
AUDIO_TRANSCRIPTION=False

[RHEA]
RHEA_DOMAIN=floorwalk.in
RHEA_PROTOCOL=https

[DATABASE]
ENGINE=django.db.backends.postgresql_psycopg2
NAME=kronos_db_test
USER=postgres
PASSWORD=postgres
HOST=localhost
PORT=5432

[EMAIL_SETTINGS]
HOST=smtp.gmail.com
PORT=587
HOST_USER=foo@bar.com
HOST_PASSWORD=password
DEFAULT_FROM_EMAIL=FloorWalk <noreply@floorwalk.in>
SERVER_EMAIL=FloorWalk <noreply@floorwalk.in>

[PAYMENT_CSV_SETTINGS]
ORDERINGACCNO=2541109900110007
REMITTER_NAME=FLOORWALK CONSULTANTS PVT LTD
SENTTORECVINFO=Floorwalk Audit fees
INDICATOR=EML
ORIGINAL_REMITTER=FLOORWALK CONSULTANTS PVT LTD

[PAYMENT_NEW_CSV_SETTINGS]
Record_Identifier=P
Debit_Account_No=409000647811
Payment_Product_Code=NEFT_CONSOLIDATE
ReasonForPayment=Floorwalk Audit fees
Debit_Narration=Floorwalk Audit fees

[S3_ATTACHMENTS]
AWS_ACCESS_KEY_ID=foobar
AWS_SECRET_ACCESS_KEY=foobar_secret
BUCKET=fw-attachments-test
REGION=ap-southeast-1
MIN_SIZE=1024
### 20 * 1024 * 1024 = 20971520 bytes
MAX_SIZE=20971520
FILE_SLUG_SIZE=10

[LOGGER_SETTINGS]
### set log level to any one of: DEBUG, INFO, WARNING, ERROR, CRITICAL
### set to INFO preferably
LOG_LEVEL=DEBUG

### set this to the file where django logs are recorded
DJANGO_LOG_FILENAME=/tmp/kronos.log

### add log handlers, can contain 'logfile' which logs to above file or 'console' or both
### should use only 'logfile' in production and only 'console' in development
LOG_HANDLERS=console,logfile

### add a switch for email sending email notifications
### when set to true, emails will be sent when the action is triggered
[EMAIL_SWITCH]
NOTIFICATION=False
VERIFICATION=False
PRE_REMINDER=False
ON_REMINDER=False
POST_REMINDER=False
WELCOME=False
OPPORTUNITY=False
AGENCY_VERIFICATION=False
AUDIT_REPORT_FAILED_BY_AUDITOR=False
AUDIT_REPORT_WITHDRAW_BY_AUDITOR_EMAIL=False
REPORTING_STATS_EMAIL=False
AUDIT_REPORT_CONCERN_BY_AUDITOR_EMAIL=False

### add a switch for text message sending
### when set to true, text message will send to auditor
[MESSAGE_SWITCH]
NOTIFICATION=False

[MSG91]
MSG_URL=https://api.msg91.com/api/v5/flow/
MSG91_FLOW_ID=foo_bar_flow_id
MSG91_AUTH_KEY=foo_bar_secret
MSG91_SENDER_ID=foobar


#Sending email to particular email address
[REPORTING_EMAIL]
EMAIL_LIST = email1@domain.in;email2@domain.in

[FRONTEND]
CLIENT_IMPACT_FACTOR_URL=https://s3-ap-southeast-1.amazonaws.com/bucket_name/object_path
CLIENT_TWEET_DATA_URL=https://s3-ap-southeast-1.amazonaws.com/bucket_name/object_path
AUDITOR_FB_CLIENT_ID=999999999999999
AUDITOR_FB_FIELDS=id,name,first_name,last_name,gender,age_range,email,picture,likes,friends,location,birthday,link,verified
AUDITOR_FB_SCOPE=email,public_profile,user_friends,user_likes,user_location,user_birthday
FB_PAGE_URL=https://www.facebook.com/FloorWalk/
TW_PAGE_URL=https://twitter.com/FloorWalkIndia
TW_USERNAME=FloorWalkIndia
SUPPORT_EMAIL=contactus@floorwalk.in
ACCOUNTS_EMAIL=accounts@floorwalk.in
AUDITS_EMAIL=audits@floorwalk.in
SUPPORT_PHONE=+91-8496003316
AUDITOR_LOGIN_SUCCESS_REDIRECT_URL=/static/auditor/index.html
MANAGER_LOGIN_SUCCESS_REDIRECT_URL=/static/manager/index.html
CLIENT_LOGIN_SUCCESS_REDIRECT_URL=/static/client/index.html
MODERATOR_LOGIN_SUCCESS_REDIRECT_URL=/static/moderator/index.html
AGENCY_LOGIN_SUCCESS_REDIRECT_URL=/static/agency/index.html

### Collect CDN Bot ID
COLLECTCDN_ID=secret-secret-i-got-a-secret

### Google Analytics Tracking ID for Authentication/Registration views only
### The actual app should use different tracking IDs for manager,auditor and client UIs
AUDITOR_GA_ID=UA-XXXXXXXX-X
CLIENT_GA_ID=UA-XXXXXXXX-X

### Tawk.to src for live chat with auditors
TAWK_TO_SRC=https://embed.tawk.to/foobar/default

### Sentry DSN for JS error monitoring
SENTRY_DSN=https://68a03ad318ef45cc8e5f3dbc12f8f405@sentry.io/288151

[REFERRAL]
SIGNUP_AMOUNT = 10
AUDIT_AMOUNT = 100
MAX_AUDIT_REFERRALS = 3

[TWITTER_FEEDS]
CONSUMER_KEY=XXXXXXXXXXX
CONSUMER_SECRET=XXXXXXXXXXX
ACCESS_TOKEN=XXXXXXXXXXX
ACCESS_TOKEN_SECRET=XXXXXXXXXXX

[CELERY]
BROKER_URL=amqps://username:password@localhost/foo/bar
TASK_ALWAYS_EAGER=False


[CONVERTAPI]
CONVERT_API_SECRET = secret

[REPORTS]
REPORT_PERMISSION_EMAIL_LIST = []