"""
Django settings for kronos project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import properties
from django import urls

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = properties.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = properties.DEBUG

ALLOWED_HOSTS = ['*']


# Application definition

DEPENDENCY_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'widget_tweaks',
    'notifications',
]

PROJECT_APPS = [
    'registration',
    'auditor',
    'nav',
    'manager',
    'client',
    'questionnaire',
    'audit',
    'audit_store',
    'answer',
    'attachment',
    'client_report',
    'notify'
]

INSTALLED_APPS = DEPENDENCY_APPS + PROJECT_APPS

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'registration.DisableCSRF',
]

ROOT_URLCONF = 'kronos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'registration.context.auth_ga_id',
            ],
        },
    },
]

WSGI_APPLICATION = 'kronos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': properties.database
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated' # only allow authenticated users
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication', # only allow session based authentication
    ),
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50
}

AUTHENTICATION_BACKENDS = ('registration.backends.CaseInsensitiveModelBackend',)

if DEBUG:
    # add the Web Browsable API Renderer when DEBUG is enabled
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"].append('rest_framework.renderers.BrowsableAPIRenderer')


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    os.path.join(BASE_DIR, "frontend"),
]

## django.contrib.auth settings

LOGIN_URL = '/auth/login'
LOGIN_REDIRECT_URL = '/auditor/dashboard'
LOGOUT_REDIRECT_URL = '/auth/login'

## email settings

EMAIL_HOST = properties.email_settings["EMAIL_HOST"]
EMAIL_PORT = properties.email_settings["EMAIL_PORT"]
EMAIL_HOST_USER = properties.email_settings["EMAIL_HOST_USER"]
EMAIL_HOST_PASSWORD = properties.email_settings["EMAIL_HOST_PASSWORD"]
DEFAULT_FROM_EMAIL = properties.email_settings["DEFAULT_FROM_EMAIL"]
SERVER_EMAIL = properties.email_settings["SERVER_EMAIL"]
EMAIL_USE_TLS = True


LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'simple': {
                'format': '[%(asctime)s][%(levelname)s] %(message)s'
                },
            },
        'handlers': {
                'console':{
                        'level': properties.log_level,
                        'class': 'logging.StreamHandler',
                        'formatter': 'simple'
                },
                'logfile':{
                        'level': properties.log_level,
                        'class': 'logging.FileHandler',
                        'filename': properties.django_log_filename,
                        'formatter': 'simple'
                },
        },
        'loggers': {
            #'django': {
            #    'level': properties.log_level,
            #    'filters': [],
            #    'handlers': properties.log_handlers,
            #    'propagate': True
            #},
            '': {
                'level': properties.log_level,
                'handlers': properties.log_handlers,
            },
         },
}

AWS = properties.AWS

AUTH_GA_ID = properties.AUTH_GA_ID
