"""
Django settings for kronos project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import sys
import logging
from configparser import ConfigParser

from django import urls

_logger = logging.getLogger(__name__)

properties = ConfigParser()
if "properties.ini" not in properties.read("properties.ini"):
     _logger.error("properties.ini not found")
     sys.exit(1)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = properties["GENERAL"]["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = properties["GENERAL"]["DEBUG"]

ALLOWED_HOSTS = ['*']


# Application definition

DEPENDENCY_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'widget_tweaks',
    'notifications',
    'guardian',
    'markdown_deux',
]

PROJECT_APPS = [
    'registration',
    'auditor',
    'nav',
    'manager',
    'client',
    'questionnaire',
    'audit',
    'audit_store',
    'answer',
    'attachment',
    'client_report',
    'notify',
    'payment',
    'monitoring',
    'moderator_rest',
    'client_rest',
    'social',
    'referral',
]

INSTALLED_APPS = DEPENDENCY_APPS + PROJECT_APPS

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'registration.DisableCSRF',
    'kronos.exceptions.KronosExceptionMiddleware',
]

ROOT_URLCONF = 'kronos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'registration.context.auth_ga_id',
            ],
        },
    },
]

WSGI_APPLICATION = 'kronos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': properties["DATABASE"]["ENGINE"],
        'NAME': properties["DATABASE"]["NAME"],
        'USER': properties["DATABASE"]["USER"],
        'PASSWORD': properties["DATABASE"]["PASSWORD"],
        'HOST': properties["DATABASE"]["HOST"],
        'PORT': int(properties["DATABASE"]["PORT"]),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated' # only allow authenticated users
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication', # only allow session based authentication
    ),
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50
}

AUTHENTICATION_BACKENDS = (
        'registration.backends.CaseInsensitiveModelBackend',
        'guardian.backends.ObjectPermissionBackend',
    )

if DEBUG:
    # add the Web Browsable API Renderer when DEBUG is enabled
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"].append('rest_framework.renderers.BrowsableAPIRenderer')


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    os.path.join(BASE_DIR, "frontend"),
]

## django.contrib.auth settings

LOGIN_URL = '/auth/login'
LOGIN_REDIRECT_URL = '/auditor/dashboard'
LOGOUT_REDIRECT_URL = '/auth/login'

## email settings

EMAIL_HOST = properties["EMAIL_SETTINGS"]["HOST"]
EMAIL_PORT = int(properties["EMAIL_SETTINGS"]["PORT"])
EMAIL_HOST_USER = properties["EMAIL_SETTINGS"]["HOST_USER"]
EMAIL_HOST_PASSWORD = properties["EMAIL_SETTINGS"]["HOST_PASSWORD"]
DEFAULT_FROM_EMAIL = properties["EMAIL_SETTINGS"]["DEFAULT_FROM_EMAIL"]
SERVER_EMAIL = properties["EMAIL_SETTINGS"]["SERVER_EMAIL"]
EMAIL_USE_TLS = True

# payment csv file settings

PAYMENT_CSV_SETTINGS = {
    "ORDERINGACCNO": properties["PAYMENT_CSV_SETTINGS"]["ORDERINGACCNO"],
    "REMITTER_NAME": properties["PAYMENT_CSV_SETTINGS"]["ORDERINGACCNO"],
    "SENTTORECVINFO": properties["PAYMENT_CSV_SETTINGS"]["SENTTORECVINFO"],
    "INDICATOR": properties["PAYMENT_CSV_SETTINGS"]["INDICATOR"],
    "ORIGINAL_REMITTER": properties["PAYMENT_CSV_SETTINGS"]["ORIGINAL_REMITTER"],
}
# payment_settings = properties.payment_settings


LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'simple': {
                'format': '[%(asctime)s][%(levelname)s] %(message)s'
                },
            },
        'handlers': {
                'console':{
                        'level': properties["LOGGER_SETTINGS"]["LOG_LEVEL"],
                        'class': 'logging.StreamHandler',
                        'formatter': 'simple'
                },
                'logfile':{
                        'level': properties["LOGGER_SETTINGS"]["LOG_LEVEL"],
                        'class': 'logging.FileHandler',
                        'filename': properties["LOGGER_SETTINGS"]["DJANGO_LOG_FILENAME"],
                        'formatter': 'simple'
                },
        },
        'loggers': {
            #'django': {
            #    'level': properties.log_level,
            #    'filters': [],
            #    'handlers': properties.log_handlers,
            #    'propagate': True
            #},
            '': {
                'level': properties["LOGGER_SETTINGS"]["LOG_LEVEL"],
                'handlers': properties["LOGGER_SETTINGS"]["LOG_HANDLERS"].split(','),
            },
         },
}

BASE_DOMAIN_NAME = properties["GENERAL"]["BASE_DOMAIN_NAME"]

AWS = {
    "S3_ATTACHMENTS": {
        "AWS_ACCESS_KEY_ID": properties["S3_ATTACHMENTS"]["AWS_ACCESS_KEY_ID"],
        "AWS_SECRET_ACCESS_KEY": properties["S3_ATTACHMENTS"]["AWS_SECRET_ACCESS_KEY"],
        "BUCKET": properties["S3_ATTACHMENTS"]["BUCKET"],
        "REGION": properties["S3_ATTACHMENTS"]["REGION"],
        "MIN_SIZE": int(properties["S3_ATTACHMENTS"]["MIN_SIZE"]),
        "MAX_SIZE": int(properties["S3_ATTACHMENTS"]["MAX_SIZE"]),
        "FILE_SLUG_SIZE": int(properties["S3_ATTACHMENTS"]["FILE_SLUG_SIZE"]),
    }
}

AUTH_GA_ID = properties["FRONTEND"]["AUDITOR_GA_ID"]
TAWK_TO_SRC = properties["FRONTEND"]["TAWK_TO_SRC"]

IMGIX_SUBDOMAIN = properties["GENERAL"]["IMGIX_SUBDOMAIN"]

EMAIL_SWITCH = {
    "NOTIFICATION_EMAIL": properties["EMAIL_SWITCH"]["NOTIFICATION"] == "True",
    "VERIFICATION_EMAIL": properties["EMAIL_SWITCH"]["VERIFICATION"] == "True",
    "PRE_REMINDER_EMAIL": properties["EMAIL_SWITCH"]["PRE_REMINDER"] == "True",
    "ON_REMINDER_EMAIL": properties["EMAIL_SWITCH"]["ON_REMINDER"] == "True",
    "POST_REMINDER_EMAIL": properties["EMAIL_SWITCH"]["POST_REMINDER"] == "True",
    "WELCOME_EMAIL": properties["EMAIL_SWITCH"]["WELCOME"] == "True",
}

FRONTEND_CONFIG = {
        "AUDITOR": {
            "TAWK_TO_SRC": TAWK_TO_SRC,
            "GA_ID": AUTH_GA_ID,
            "FB_CLIENT_ID": properties["FRONTEND"]["AUDITOR_FB_CLIENT_ID"],
            "FB_FIELDS": properties["FRONTEND"]["AUDITOR_FB_FIELDS"],
            "FB_SCOPE": properties["FRONTEND"]["AUDITOR_FB_SCOPE"],
        },
        "CLIENT": {
            "IMPACT_FACTOR_URL": properties["FRONTEND"]["CLIENT_IMPACT_FACTOR_URL"],
            "TWEET_DATA_URL": properties["FRONTEND"]["CLIENT_TWEET_DATA_URL"],
        },
}

REFERRAL_SIGNUP_AMOUNT = properties["REFERRAL"]["SIGNUP_AMOUNT"]
REFERRAL_AUDIT_AMOUNT = properties["REFERRAL"]["AUDIT_AMOUNT"]
MAX_AUDIT_REFERRALS = properties["REFERRAL"]["MAX_AUDIT_REFERRALS"]