"""
Django settings for kronos project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import sys
import logging
from configparser import ConfigParser

_logger = logging.getLogger(__name__)

properties = ConfigParser()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

CONFIG_FILE_ORDER = [
    "/etc/kronos/properties.ini",
    os.path.expanduser("~/.config/kronos/properties.ini"),
    os.path.join(BASE_DIR, "properties.ini")
]

if "KRONOS_CONFIG_FILE" in os.environ:
    CONFIG_FILE_ORDER.append(os.environ.get("KRONOS_CONFIG_FILE"))

if not properties.read(CONFIG_FILE_ORDER):
    _logger.error("no config files found at following locations: %s", CONFIG_FILE_ORDER)
    sys.exit(1)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = properties["GENERAL"]["SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = properties["GENERAL"]["DEBUG"] == "True"
DEBUG_TOOLBAR = properties["GENERAL"]["DEBUG_TOOLBAR"] == "True"

# Kronos URL values
KRONOS_DOMAIN = properties["GENERAL"]["KRONOS_DOMAIN"]
KRONOS_PROTOCOL = properties["GENERAL"]["KRONOS_PROTOCOL"]
KRONOS_BASE_URL = "{}://{}".format(KRONOS_PROTOCOL, KRONOS_DOMAIN)

# Rhea URL values
RHEA_PROTOCOL = properties["RHEA"]["RHEA_PROTOCOL"]
RHEA_DOMAIN = properties["RHEA"]["RHEA_DOMAIN"]
RHEA_BASE_URL = "{}://{}".format(RHEA_PROTOCOL, RHEA_DOMAIN)

# only allow requests with Host: KRONOS_DOMAIN.split(':')[0]
ALLOWED_HOSTS = ["localhost", KRONOS_DOMAIN.split(':')[0]]

BRAND_NAME = properties["GENERAL"]["BRAND_NAME"]
BRAND_SHORTNAME = properties["GENERAL"]["BRAND_SHORTNAME"]

# Application definition

DEPENDENCY_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'widget_tweaks',
    'notifications',
    'guardian',
    'markdown_deux',
]

if DEBUG and DEBUG_TOOLBAR:
    DEPENDENCY_APPS.append('debug_toolbar')

PROJECT_APPS = [
    'registration',
    'auditor',
    'manager',
    'client',
    'questionnaire',
    'audit',
    'audit_store',
    'answer',
    'attachment',
    'client_report',
    'notify',
    'payment',
    'monitoring',
    'moderator_rest',
    'client_rest',
    'social',
    'referral',
]

INSTALLED_APPS = DEPENDENCY_APPS + PROJECT_APPS

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'registration.DisableCSRF',
    'kronos.exceptions.KronosExceptionMiddleware',
]

if DEBUG and DEBUG_TOOLBAR:
    MIDDLEWARE_CLASSES.append('debug_toolbar.middleware.DebugToolbarMiddleware')

ROOT_URLCONF = 'kronos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'registration.context.registration_request_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'kronos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': properties["DATABASE"]["ENGINE"],
        'NAME': properties["DATABASE"]["NAME"],
        'USER': properties["DATABASE"]["USER"],
        'PASSWORD': properties["DATABASE"]["PASSWORD"],
        'HOST': properties["DATABASE"]["HOST"],
        'PORT': int(properties["DATABASE"]["PORT"]),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    # { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    # { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # only allow authenticated users
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',  # only allow session based authentication
    ),
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50
}

AUTHENTICATION_BACKENDS = (
    'registration.backends.CaseInsensitiveModelBackend',
    'guardian.backends.ObjectPermissionBackend',
)

if DEBUG:
    # add the Web Browsable API Renderer when DEBUG is enabled
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"].append('rest_framework.renderers.BrowsableAPIRenderer')


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = properties["GENERAL"]["STATIC_ROOT"]

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "frontend", "dist"),
]

# email settings
EMAIL_HOST = properties["EMAIL_SETTINGS"]["HOST"]
EMAIL_PORT = int(properties["EMAIL_SETTINGS"]["PORT"])
EMAIL_HOST_USER = properties["EMAIL_SETTINGS"]["HOST_USER"]
EMAIL_HOST_PASSWORD = properties["EMAIL_SETTINGS"]["HOST_PASSWORD"]
DEFAULT_FROM_EMAIL = properties["EMAIL_SETTINGS"]["DEFAULT_FROM_EMAIL"]
SERVER_EMAIL = properties["EMAIL_SETTINGS"]["SERVER_EMAIL"]
EMAIL_USE_TLS = True

# payment csv file settings
PAYMENT_CSV_SETTINGS = {
    "ORDERINGACCNO": properties["PAYMENT_CSV_SETTINGS"]["ORDERINGACCNO"],
    "REMITTER_NAME": properties["PAYMENT_CSV_SETTINGS"]["ORDERINGACCNO"],
    "SENTTORECVINFO": properties["PAYMENT_CSV_SETTINGS"]["SENTTORECVINFO"],
    "INDICATOR": properties["PAYMENT_CSV_SETTINGS"]["INDICATOR"],
    "ORIGINAL_REMITTER": properties["PAYMENT_CSV_SETTINGS"]["ORIGINAL_REMITTER"],
}

PAYMENT_NEW_CSV_SETTINGS = {
    "Record_Identifier": properties["PAYMENT_NEW_CSV_SETTINGS"]["Record_Identifier"],
    "Debit_Account_No": properties["PAYMENT_NEW_CSV_SETTINGS"]["Debit_Account_No"],
    "Payment_Product_Code": properties["PAYMENT_NEW_CSV_SETTINGS"]["Payment_Product_Code"],
    "ReasonForPayment": properties["PAYMENT_NEW_CSV_SETTINGS"]["ReasonForPayment"],
    "Debit_Narration": properties["PAYMENT_NEW_CSV_SETTINGS"]["Debit_Narration"],
}


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[%(asctime)s][%(levelname)s] %(message)s'
        },
    },
    'handlers': {
        'console':{
            'level': properties["LOGGER_SETTINGS"]["LOG_LEVEL"],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'logfile':{
            'level': properties["LOGGER_SETTINGS"]["LOG_LEVEL"],
            'class': 'logging.FileHandler',
            'filename': properties["LOGGER_SETTINGS"]["DJANGO_LOG_FILENAME"],
            'formatter': 'simple'
        },
    },
    'loggers': {
        # 'django': {
        #     'level': properties.log_level,
        #     'filters': [],
        #     'handlers': properties.log_handlers,
        #     'propagate': True
        # },
        '': {
            'level': properties["LOGGER_SETTINGS"]["LOG_LEVEL"],
            'handlers': properties["LOGGER_SETTINGS"]["LOG_HANDLERS"].split(','),
        },
    },
}

AWS = {
    "S3_ATTACHMENTS": {
        "AWS_ACCESS_KEY_ID": properties["S3_ATTACHMENTS"]["AWS_ACCESS_KEY_ID"],
        "AWS_SECRET_ACCESS_KEY": properties["S3_ATTACHMENTS"]["AWS_SECRET_ACCESS_KEY"],
        "BUCKET": properties["S3_ATTACHMENTS"]["BUCKET"],
        "REGION": properties["S3_ATTACHMENTS"]["REGION"],
        "MIN_SIZE": int(properties["S3_ATTACHMENTS"]["MIN_SIZE"]),
        "MAX_SIZE": int(properties["S3_ATTACHMENTS"]["MAX_SIZE"]),
        "FILE_SLUG_SIZE": int(properties["S3_ATTACHMENTS"]["FILE_SLUG_SIZE"]),
    }
}

AUTH_GA_ID = properties["FRONTEND"]["AUDITOR_GA_ID"]
TAWK_TO_SRC = properties["FRONTEND"]["TAWK_TO_SRC"]

IMGIX_SUBDOMAIN = properties["GENERAL"]["IMGIX_SUBDOMAIN"]

EMAIL_SWITCH = {
    "NOTIFICATION_EMAIL": properties["EMAIL_SWITCH"]["NOTIFICATION"] == "True",
    "VERIFICATION_EMAIL": properties["EMAIL_SWITCH"]["VERIFICATION"] == "True",
    "PRE_REMINDER_EMAIL": properties["EMAIL_SWITCH"]["PRE_REMINDER"] == "True",
    "ON_REMINDER_EMAIL": properties["EMAIL_SWITCH"]["ON_REMINDER"] == "True",
    "POST_REMINDER_EMAIL": properties["EMAIL_SWITCH"]["POST_REMINDER"] == "True",
    "WELCOME_EMAIL": properties["EMAIL_SWITCH"]["WELCOME"] == "True",
    "OPPORTUNITY_EMAIL": properties["EMAIL_SWITCH"]["OPPORTUNITY"] == "True",
}

FRONTEND_CONFIG = {
    "COMMON": {
        "FB_PAGE_URL": properties["FRONTEND"]["FB_PAGE_URL"],
        "TW_PAGE_URL": properties["FRONTEND"]["TW_PAGE_URL"],
        "TW_USERNAME": properties["FRONTEND"]["TW_USERNAME"],
        "SUPPORT_EMAIL": properties["FRONTEND"]["SUPPORT_EMAIL"],
        "SUPPORT_PHONE": properties["FRONTEND"]["SUPPORT_PHONE"],
    },
    "AUDITOR": {
        "TAWK_TO_SRC": TAWK_TO_SRC,
        "GA_ID": AUTH_GA_ID,
        "FB_CLIENT_ID": properties["FRONTEND"]["AUDITOR_FB_CLIENT_ID"],
        "FB_FIELDS": properties["FRONTEND"]["AUDITOR_FB_FIELDS"],
        "FB_SCOPE": properties["FRONTEND"]["AUDITOR_FB_SCOPE"],
        "RHEA_BASE_URL": RHEA_BASE_URL,
        "LOGIN_SUCCESS_REDIRECT_URL": properties["FRONTEND"]["AUDITOR_LOGIN_SUCCESS_REDIRECT_URL"]
    },
    "CLIENT": {
        "IMPACT_FACTOR_URL": properties["FRONTEND"]["CLIENT_IMPACT_FACTOR_URL"],
        "TWEET_DATA_URL": properties["FRONTEND"]["CLIENT_TWEET_DATA_URL"],
        "RHEA_BASE_URL": RHEA_BASE_URL,
        "LOGIN_SUCCESS_REDIRECT_URL": properties["FRONTEND"]["CLIENT_LOGIN_SUCCESS_REDIRECT_URL"]
    },
    "MANAGER": {
        "RHEA_BASE_URL": RHEA_BASE_URL,
        "LOGIN_SUCCESS_REDIRECT_URL": properties["FRONTEND"]["MANAGER_LOGIN_SUCCESS_REDIRECT_URL"]
    },
    "MODERATOR": {
        "LOGIN_SUCCESS_REDIRECT_URL": properties["FRONTEND"]["MODERATOR_LOGIN_SUCCESS_REDIRECT_URL"]
    }
}

REFERRAL_SIGNUP_AMOUNT = properties["REFERRAL"]["SIGNUP_AMOUNT"]
REFERRAL_AUDIT_AMOUNT = properties["REFERRAL"]["AUDIT_AMOUNT"]
MAX_AUDIT_REFERRALS = properties["REFERRAL"]["MAX_AUDIT_REFERRALS"]

TWITTER_FEEDS = {
    "CONSUMER_KEY": properties["TWITTER_FEEDS"]["CONSUMER_KEY"],
    "CONSUMER_SECRET": properties["TWITTER_FEEDS"]["CONSUMER_SECRET"],
    "ACCESS_TOKEN": properties["TWITTER_FEEDS"]["ACCESS_TOKEN"],
    "ACCESS_TOKEN_SECRET": properties["TWITTER_FEEDS"]["ACCESS_TOKEN_SECRET"],
}

INTERNAL_IPS = ['127.0.0.1', 'localhost']

DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.logging.LoggingPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
    'debug_toolbar.panels.profiling.ProfilingPanel',
]
