
 
var types = {
	//Client GET Action Types
	CLIENT_GET_REQ: 'CLIENT_GET_REQ',
	CLIENT_GET_ERR: 'CLIENT_GET_ERR',
	CLIENT_GET_SUC: 'CLIENT_GET_SUC',

	//Client POST Action Types
	CLIENT_POST_REQ: 'CLIENT_POST_REQ',
	CLIENT_POST_ERR: 'CLIENT_POST_ERR',
	CLIENT_POST_SUC: 'CLIENT_POST_SUC',

	//Client ID GET Action Types
	CLIENT_ID_GET_REQ: 'CLIENT_ID_GET_REQ',
	CLIENT_ID_GET_ERR: 'CLIENT_ID_GET_ERR',
	CLIENT_ID_GET_SUC: 'CLIENT_ID_GET_SUC',

	//Client ID POST Action Types
	CLIENT_ID_POST_REQ: 'CLIENT_ID_POST_REQ',
	CLIENT_ID_POST_ERR: 'CLIENT_ID_POST_ERR',
	CLIENT_ID_POST_SUC: 'CLIENT_ID_POST_SUC',

	//Client Form Load Action Types
	CLIENT_FORM_LOAD_REQ: 'CLIENT_FORM_LOAD_REQ',
	CLIENT_FORM_LOAD_ERR: 'CLIENT_FORM_LOAD_ERR',
	CLIENT_FORM_LOAD_SUC: 'CLIENT_FORM_LOAD_SUC',

	//Client Form Submit Action Types
	CLIENT_FORM_SUB_REQ: 'CLIENT_FORM_SUB_REQ',
	CLIENT_FORM_SUB_ERR: 'CLIENT_FORM_SUB_ERR',
	CLIENT_FORM_SUB_SUC: 'CLIENT_FORM_SUB_SUC',

	//Auditor GET
	AUDITOR_SEARCH: 'AUDITOR_SEARCH',

	AUDITOR_ID_GET: 'AUDITOR_ID_GET',

	//Auditor sub information
	AUDITOR_GET_PROFILE_INFO: 'AUDITOR_GET_PROFILE_INFO',
	AUDITOR_GET_BANK_INFO: 'AUDITOR_GET_BANK_INFO',
	AUDITOR_GET_ADDITIONAL_INFO: 'AUDITOR_GET_ADDITIONAL_INFO',

	//Location get
	LOCATION_GET: 'LOCATION_GET',
	LOCATION_POST: 'LOCATION_POST',

	//Location Id get
	LOCATION_ID_GET: 'LOCATION_ID_GET',

	//Location Id post
	LOCATION_ID_POST: 'LOCATION_ID_POST',

	//Location Form
	LOCATION_FORM_LOAD: 'LOCATION_FORM_LOAD',
	LOCATION_FORM_SUB: 'LOCATION_FORM_SUB',

	//Store get
	STORE_GET: 'STORE_GET',
	STORE_POST: 'STORE_POST',
	STORE_ID_GET: 'STORE_ID_GET',
	STORE_ID_POST: 'STORE_ID_POST',
	STORE_FORM_LOAD: 'STORE_FORM_LOAD',
	STORE_FORM_SUB: 'STORE_FORM_SUB',

	//City get
	CITY_GET: 'CITY_GET',
	STATE_GET: 'STATE_GET',

	//Audit
	AUDIT_GET: 'AUDIT_GET',
	AUDIT_POST: 'AUDIT_POST',

	//Audit Id
	AUDIT_ID_GET: 'AUDIT_ID_GET',
	AUDIT_ID_POST: 'AUDIT_ID_POST',

	//Audit Form
	AUDIT_FORM_LOAD: 'AUDIT_FORM_LOAD',
	AUDIT_FORM_SUB: 'AUDIT_FORM_SUB',

	// Audit Location Form
	AUDIT_LOCATION_FORM_LOAD: 'AUDIT_LOCATION_FORM_LOAD',
	AUDIT_LOCATION_FORM_SUB: 'AUDIT_LOCATION_FORM_SUB',

	//Audit Location
	AUDIT_LOCATION_POST: 'AUDIT_LOCATION_POST',
	AUDIT_LOCATION_ID_POST: 'AUDIT_LOCATION_ID_POST',

	//Audit Applications
	AUDIT_APPLICATION_GET: 'AUDIT_LOCATION_GET',
	AUDIT_APPLICATION_ASSIGN: 'AUDIT_APPLICATION_ASSIGN',
	AUDIT_APPLICATION_REJECT: 'AUDIT_APPLICATION_REJECT',
	AUDIT_APPLICATION_COMPLETE: 'AUDIT_APPLICATION_COMPLETE',
	AUDIT_APPLICATION_FAIL: 'AUDIT_APPLICATION_FAIL',
};

export default types;
