

var types = {
	//Client Action Types
	CLIENT_GET: 'CLIENT_GET',
	CLIENT_POST: 'CLIENT_POST',

	//Client ID Action Types
	CLIENT_ID_GET: 'CLIENT_ID_GET',
	CLIENT_ID_POST: 'CLIENT_ID_POST',

	//Client Form Load Action Types
	CLIENT_FORM_LOAD: 'CLIENT_FORM_LOAD',

	//Client Form Submit Action Types
	CLIENT_FORM_SUB: 'CLIENT_FORM_SUB',

	//Client User
	CLIENT_USER_GET: 'CLIENT_USER_GET',
	CLIENT_USER_POST: 'CLIENT_USER_POST',
	CLIENT_USER_ID_GET: 'CLIENT_USER_ID_GET',
	CLIENT_USER_ID_POST: 'CLIENT_USER_ID_POST',

	CLIENT_USER_FORM_LOAD: 'CLIENT_USER_FORM_LOAD',
	CLIENT_USER_FORM_SUB: 'CLIENT_USER_FORM_SUB',

	//Auditor GET
	AUDITOR_SEARCH: 'AUDITOR_SEARCH',

	AUDITOR_ID_GET: 'AUDITOR_ID_GET',

	AUDITOR_ID_ACTIVATE: 'AUDITOR_ID_ACTIVATE',
	AUDITOR_ID_DEACTIVATE: 'AUDITOR_ID_DEACTIVATE',
	AUDITOR_ID_VERIFY: 'AUDITOR_ID_VERIFY',

	//Auditor sub information
	AUDITOR_GET_PROFILE_INFO: 'AUDITOR_GET_PROFILE_INFO',
	AUDITOR_GET_BANK_INFO: 'AUDITOR_GET_BANK_INFO',
	AUDITOR_GET_ADDITIONAL_INFO: 'AUDITOR_GET_ADDITIONAL_INFO',

	//Location get
	LOCATION_GET: 'LOCATION_GET',
	LOCATION_POST: 'LOCATION_POST',

	//Location Id get
	LOCATION_ID_GET: 'LOCATION_ID_GET',

	//Location Id post
	LOCATION_ID_POST: 'LOCATION_ID_POST',

	//Location Form
	LOCATION_FORM_LOAD: 'LOCATION_FORM_LOAD',
	LOCATION_FORM_SUB: 'LOCATION_FORM_SUB',

	//Store get
	STORE_GET: 'STORE_GET',
	STORE_POST: 'STORE_POST',
	STORE_ID_GET: 'STORE_ID_GET',
	STORE_ID_POST: 'STORE_ID_POST',
	STORE_ID_DELETE: 'STORE_ID_DELETE',
	STORE_FORM_LOAD: 'STORE_FORM_LOAD',
	STORE_FORM_SUB: 'STORE_FORM_SUB',

	//City get
	CITY_GET: 'CITY_GET',
	STATE_GET: 'STATE_GET',

	//Audit Cycle
	AUDIT_CYCLE_GET: 'AUDIT_CYCLE_GET',
	AUDIT_CYCLE_POST: 'AUDIT_CYCLE_POST',
	AUDIT_CYCLE_ID_GET: 'AUDIT_CYCLE_ID_GET',
	AUDIT_CYCLE_ID_POST: 'AUDIT_CYCLE_ID_POST',
	AUDIT_CYCLE_FORM_LOAD: 'AUDIT_CYCLE_FORM_LOAD',
	AUDIT_CYCLE_FORM_SUB: 'AUDIT_CYCLE_FORM_SUB',

	//Audit Store
	AUDIT_STORE_GET: 'AUDIT_STORE_GET',
	AUDIT_STORE_ID_GET: 'AUDIT_STORE_ID_GET',
	AUDIT_STORE_ID_WITHDRAW: 'AUDIT_STORE_ID_WITHDRAW',
	AUDIT_STORE_ID_COMPLETE: 'AUDIT_STORE_ID_COMPLETE',
	AUDIT_STORE_ID_UNCOMPLETE: 'AUDIT_STORE_ID_UNCOMPLETE',
	AUDIT_STORE_ID_FAIL: 'AUDIT_STORE_ID_FAIL',
	AUDIT_STORE_ID_SUBMIT: 'AUDIT_STORE_ID_SUBMIT',
	AUDIT_STORE_ID_UN_SUBMIT: 'AUDIT_STORE_ID_UN_SUBMIT',
	AUDIT_STORE_ID_PAY: 'AUDIT_STORE_ID_PAY',
	AUDIT_STORE_ID_UNPAY: 'AUDIT_STORE_ID_UNPAY',
	AUDIT_STORE_ID_ACCEPT: 'AUDIT_STORE_ID_ACCEPT',
	AUDIT_STORE_ID_REJECT: 'AUDIT_STORE_ID_REJECT',

	//glue types
	AUDIT_STORE_UPDATED: 'AUDIT_STORE_UPDATED',

	//section
	SECTION_GET: 'SECTION_GET',
	SECTION_POST: 'SECTION_POST',
	SECTION_ID_GET: 'SECTION_ID_GET',
	SECTION_ID_POST: 'SECTION_ID_POST',
	SECTION_ID_DELETE: 'SECTION_ID_DELETE',
	SECTION_FORM_LOAD: 'SECTION_FORM_LOAD',
	SECTION_FORM_SUB: 'SECTION_FORM_SUB',

	//Audit
	AUDIT_GET: 'AUDIT_GET',
	AUDIT_POST: 'AUDIT_POST',

	//Audit Id
	AUDIT_ID_GET: 'AUDIT_ID_GET',
	AUDIT_ID_POST: 'AUDIT_ID_POST',
	AUDIT_ID_DELETE: 'AUDIT_ID_DELETE',

	//Audit Form
	AUDIT_FORM_LOAD: 'AUDIT_FORM_LOAD',
	AUDIT_FORM_SUB: 'AUDIT_FORM_SUB',

	//Audit Applications
	AUDIT_APPLICATION_GET: 'AUDIT_LOCATION_GET',
	AUDIT_APPLICATION_APPROVE: 'AUDIT_APPLICATION_APPROVE',
	AUDIT_APPLICATION_REJECT: 'AUDIT_APPLICATION_REJECT',

	//Answer
	ANSWER_GET: 'ANSWER_GET',
	ANSWER_MARK: 'ANSWER_MARK',
	ANSWER_NOT_APPLICABLE: 'ANSWER_NOT_APPLICABLE',

	//Report Sections
	REPORT_SECTION_GET: 'REPORT_SECTION_GET',
	REPORT_SECTION_PM_COMMENT: 'REPORT_SECTION_PM_COMMENT',
	REPORT_SECTION_AUDITOR_COMMENT: 'REPORT_SECTION_AUDITOR_COMMENT',
	REPORT_SECTION_NOT_APPLICABLE: 'REPORT_SECTION_NOT_APPLICABLE',
};

export default types;
