
export const FETCH_QUESTIONNAIRE_TYPES = "FETCH_QUESTIONNAIRE_TYPES";
export const SELECT_QUESTIONNAIRE_TYPE = "SELECT_QUESTIONNAIRE_TYPE";

export const FETCH_AUDIT_CYCLES = "FETCH_AUDIT_CYCLES";
export const SELECT_AUDIT_CYCLE = "SELECT_AUDIT_CYCLE";
