
export const FETCH_QUESTIONNAIRE_TYPES = "FETCH_QUESTIONNAIRE_TYPES";
export const SELECT_QUESTIONNAIRE_TYPE = "SELECT_QUESTIONNAIRE_TYPE";

export const FETCH_AUDIT_CYCLES = "FETCH_AUDIT_CYCLES";
export const SELECT_AUDIT_CYCLE = "SELECT_AUDIT_CYCLE";

export const FETCH_REPORTS = "FETCH_REPORTS";
export const SELECT_CITY = "SELECT_CITY";
export const SELECT_STORE_TYPE = "SELECT_STORE_TYPE";
export const SELECT_PRIORITY = "SELECT_PRIORITY";
export const SELECT_START_DATE = "SELECT_START_DATE";
export const SELECT_END_DATE = "SELECT_END_DATE";
export const RESET_FILTERS = "RESET_FILTERS";
