# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-10 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorReferral',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('comment', models.CharField(db_column='comment', max_length=500)),
                ('amount', models.IntegerField(db_column='amount')),
                ('type', models.CharField(choices=[('SIGNUP', 'Signup'), ('AUDIT', 'Audit'), ('PAID', 'Paid')], db_column='type', max_length=20)),
                ('added_on', models.DateTimeField(auto_now_add=True, db_column='added_on')),
                ('referred_by', models.ForeignKey(db_column='referred_by', on_delete=django.db.models.deletion.PROTECT, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referred_to', models.ForeignKey(db_column='referred_to', on_delete=django.db.models.deletion.PROTECT, related_name='referred_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
