# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='is_verified',
            field=models.BooleanField(db_column=b'is_verified', default=False),
        ),
    ]
