# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_verification_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='is_verified',
            field=models.BooleanField(db_column='is_verified', default=False),
        ),
    ]
