# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration','0003_auto_20160907_0953'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE auth_user ADD UNIQUE (email);"),
    ]
