# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-02 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0005_auto_20170829_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNumber',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(db_column='mobile_number', max_length=10)),
                ('activation_key', models.CharField(db_column='activation_key', max_length=40, unique=True)),
                ('key_expires', models.DateTimeField(db_column='key_expires')),
                ('is_verified', models.BooleanField(db_column='is_verified', default=False)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='mobile_numbers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='verification',
            name='activation_key',
            field=models.CharField(db_column='activation_key', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='key_expires',
            field=models.DateTimeField(db_column='key_expires'),
        ),
    ]
