# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-26 06:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0006_auto_20180302_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('otp', models.CharField(db_column='otp', max_length=4)),
                ('is_verified', models.BooleanField(db_column='is_verified', default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='otpverification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
