# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-26 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='otp',
            field=models.CharField(blank=True, db_column='otp', max_length=4),
        ),
    ]
