# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-26 09:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20230726_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='otp_expires',
            field=models.DateTimeField(db_column='otp_expires', default=datetime.date(2023, 7, 26)),
            preserve_default=False,
        ),
    ]
