# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaire', '0003_auto_20170203_0943'),
        ('audit_store', '0002_auto_20170203_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('answer_text', models.CharField(db_column='answer_text', max_length=2048)),
                ('marks_obtained', models.IntegerField(blank=True, db_column='marks_obtained', null=True)),
                ('audit_store', models.ForeignKey(db_column='audit_store_id', on_delete=django.db.models.deletion.CASCADE, to='audit_store.AuditStore')),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Question')),
            ],
        ),
    ]
