# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(blank=True, db_column='answer_text', max_length=2048),
        ),
    ]
