# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20170203_0943'),
        ('audit_store', '0005_auto_20170205_1451'),
        ('answer', '0002_auto_20170205_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('pm_comment', models.CharField(blank=True, db_column='pm_comment', max_length=2048)),
                ('auditor_comment', models.CharField(blank=True, db_column='auditor_comment', max_length=2048)),
                ('audit_store', models.ForeignKey(db_column='audit_store_id', on_delete=django.db.models.deletion.CASCADE, to='audit_store.AuditStore')),
                ('section', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Section')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='reportsection',
            unique_together=set([('audit_store', 'section')]),
        ),
    ]
