# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20170203_0943'),
        ('audit_store', '0005_auto_20170205_1451'),
        ('answer', '0003_auto_20170209_1153'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('question', 'audit_store')]),
        ),
    ]
