# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0004_auto_20170217_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsection',
            name='audit_store',
            field=models.ForeignKey(db_column='audit_store_id', on_delete=django.db.models.deletion.CASCADE, related_name='report_sections', to='audit_store.AuditStore'),
        ),
    ]
