# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0006_auto_20170227_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_text_original',
            field=models.CharField(blank=True, db_column='answer_text_original', max_length=2048),
        ),
        migrations.AddField(
            model_name='reportsection',
            name='auditor_comment_original',
            field=models.CharField(blank=True, db_column='auditor_comment_original', max_length=2048),
        ),
    ]
