# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0007_auto_20170427_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsection',
            name='not_applicable',
            field=models.BooleanField(db_column='not_applicable', default=False),
        ),
    ]
