# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0008_reportsection_not_applicable'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='not_applicable',
            field=models.BooleanField(db_column='not_applicable', default=False),
        ),
    ]
