# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0009_answer_not_applicable'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_comment',
            field=models.CharField(blank=True, db_column='answer_comment', max_length=2048),
        ),
    ]
