# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0010_answer_answer_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='audit_store',
            field=models.ForeignKey(db_column='audit_store_id', on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='audit_store.AuditStore'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.PROTECT, to='questionnaire.Question'),
        ),
        migrations.AlterField(
            model_name='reportsection',
            name='audit_store',
            field=models.ForeignKey(db_column='audit_store_id', on_delete=django.db.models.deletion.PROTECT, related_name='report_sections', to='audit_store.AuditStore'),
        ),
        migrations.AlterField(
            model_name='reportsection',
            name='section',
            field=models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.PROTECT, to='questionnaire.Section'),
        ),
    ]
