# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-10 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0011_auto_20170829_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(db_column='created_at', null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='modified_at',
            field=models.DateTimeField(db_column='modified_at', null=True),
        ),
        migrations.AddField(
            model_name='reportsection',
            name='created_at',
            field=models.DateTimeField(db_column='created_at', null=True),
        ),
        migrations.AddField(
            model_name='reportsection',
            name='modified_at',
            field=models.DateTimeField(db_column='modified_at', null=True),
        ),
    ]
