# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-25 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0012_auto_20171010_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='questionnaire.Question'),
        ),
        migrations.AlterField(
            model_name='reportsection',
            name='section',
            field=models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.PROTECT, related_name='report_sections', to='questionnaire.Section'),
        ),
    ]
