# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-15 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0013_auto_20171025_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsection',
            name='auditor_comment',
            field=models.CharField(blank=True, db_column='auditor_comment', max_length=4096),
        ),
        migrations.AlterField(
            model_name='reportsection',
            name='auditor_comment_original',
            field=models.CharField(blank=True, db_column='auditor_comment_original', max_length=4096),
        ),
        migrations.AlterField(
            model_name='reportsection',
            name='pm_comment',
            field=models.CharField(blank=True, db_column='pm_comment', max_length=4096),
        ),
    ]
