# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-22 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0014_auto_20190215_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsection',
            name='report_section_percentage',
            field=models.IntegerField(blank=True, db_column='percentage', null=True),
        ),
    ]
