# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-07-26 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0016_answer_revert_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsection',
            name='revert_message',
            field=models.CharField(blank=True, db_column='revert_message', max_length=2048),
        ),
    ]
