# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-04-28 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0017_reportsection_revert_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ai_answer_result',
            field=models.CharField(blank=True, db_column='ai_answer_result', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='ai_answer_text',
            field=models.CharField(blank=True, db_column='ai_answer_text', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='ai_match_percentage',
            field=models.IntegerField(blank=True, db_column='ai_match_percentage', null=True),
        ),
    ]
