# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-05-11 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0018_auto_20260428_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ai_answer_auditor_text',
            field=models.CharField(blank=True, db_column='ai_answer_auditor_text', max_length=20048, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='ai_decision_auditor',
            field=models.CharField(blank=True, db_column='ai_decision_auditor', max_length=20048, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='ai_final_confidence_percentage',
            field=models.IntegerField(blank=True, db_column='ai_final_confidence_percentage', null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ai_answer_result',
            field=models.CharField(blank=True, db_column='ai_answer_result', max_length=20048, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ai_answer_text',
            field=models.CharField(blank=True, db_column='ai_answer_text', max_length=20048, null=True),
        ),
    ]
