# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-08-17 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0019_auto_20260511_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(blank=True, db_column='answer_text', max_length=4000),
        ),
    ]
