# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-08-19 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0020_auto_20260817_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_comment',
            field=models.CharField(blank=True, db_column='answer_comment', max_length=4000),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text_original',
            field=models.CharField(blank=True, db_column='answer_text_original', max_length=4000),
        ),
        migrations.AlterField(
            model_name='answer',
            name='revert_message',
            field=models.CharField(blank=True, db_column='revert_message', max_length=4000),
        ),
    ]
