# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('answer_txt', models.CharField(db_column='answer_txt', max_length=200)),
                ('marks', models.PositiveIntegerField(db_column='marks')),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AuditCycle',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'walkin'), (2, 'phone'), (3, 'web'), (4, 'visibility'), (5, 'competition')], db_column='type')),
                ('status', models.IntegerField(choices=[(1, 'upcoming'), (2, 'active'), (3, 'archived')], db_column='status')),
                ('start_date', models.DateField(db_column='start_date')),
                ('end_date', models.DateField(db_column='end_date')),
                ('earnings_per_audit', models.IntegerField(db_column='earnings_per_audit')),
                ('description', models.CharField(db_column='description', max_length=200)),
            ],
        ),
    ]
