# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaire', '0001_initial'),
        ('client', '0001_initial'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcycle',
            name='client',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='client.Client'),
        ),
        migrations.AddField(
            model_name='audit',
            name='audit_cycle',
            field=models.ForeignKey(db_column='audit_cycle_id', on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='audit.AuditCycle'),
        ),
        migrations.AddField(
            model_name='audit',
            name='store',
            field=models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='client.Store'),
        ),
        migrations.AddField(
            model_name='answer',
            name='audit',
            field=models.ForeignKey(db_column='audit_id', on_delete=django.db.models.deletion.CASCADE, to='audit.Audit'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='audit',
            unique_together=set([('store', 'audit_cycle')]),
        ),
    ]
