# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20170126_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='audit',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='audit',
            name='count',
            field=models.PositiveIntegerField(db_column='count', default=1),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
