# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-05 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auto_20170127_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditcycle',
            name='status',
            field=models.CharField(choices=[('PREPARATION', 'Preparation'), ('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('REPORT', 'Report'), ('ARCHIVED', 'Archived')], db_column='status', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditcycle',
            name='type',
            field=models.CharField(choices=[('WALKIN', 'Walkin'), ('PHONE', 'Phone'), ('WEB', 'Web'), ('VISIBILITY', 'Visibility'), ('COMPETITION', 'Competition')], db_column='type', max_length=20),
        ),
    ]
