# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20170205_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='earnings_per_audit',
            field=models.IntegerField(blank=True, db_column='earnings_per_audit', null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='reimbursement',
            field=models.IntegerField(blank=True, db_column='reimbursement', null=True),
        ),
        migrations.AddField(
            model_name='auditcycle',
            name='name',
            field=models.CharField(db_column='name', default='Default Cycle Name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditcycle',
            name='reimbursement',
            field=models.IntegerField(blank=True, db_column='reimbursement', null=True),
        ),
        migrations.AlterField(
            model_name='auditcycle',
            name='earnings_per_audit',
            field=models.IntegerField(blank=True, db_column='earnings_per_audit', null=True),
        ),
    ]
