# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-11 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auto_20170210_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditcycle',
            name='description',
            field=models.CharField(db_column='description', max_length=4096),
        ),
    ]
