# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_auto_20170426_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditcycle',
            name='type',
            field=models.CharField(choices=[('WALKIN', 'Walkin'), ('PHONE', 'Phone'), ('WEB', 'Web'), ('VISIBILITY', 'Visibility'), ('COMPETITION', 'Competition'), ('SERVICE', 'Service'), ('SALES', 'Sales')], db_column='type', max_length=20),
        ),
    ]
