# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-09 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_auto_20170523_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcycle',
            name='post_approval_description',
            field=models.CharField(blank=True, db_column='post_approval_description', max_length=4096),
        ),
    ]
