# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-04 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_auto_20170625_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditcycle',
            name='type',
            field=models.CharField(choices=[('WALKIN', 'Walkin'), ('PHONE', 'Phone'), ('WEB', 'Web'), ('VISIBILITY', 'Visibility'), ('COMPETITION', 'Competition'), ('SERVICE', 'Service'), ('SALES', 'Sales'), ('FINE_DINE', 'Fine Dine'), ('SKY_KARTING', 'Sky Karting'), ('SMAAASH_ARENA', 'Smaaash Arena'), ('GENERAL', 'General')], db_column='type', max_length=20),
        ),
    ]
