# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0012_auto_20170804_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='audit_cycle',
            field=models.ForeignKey(db_column='audit_cycle_id', on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='audit.AuditCycle'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='store',
            field=models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='client.Store'),
        ),
        migrations.AlterField(
            model_name='auditcycle',
            name='client',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='client.Client'),
        ),
    ]
