# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-19 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0013_auto_20170829_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcycle',
            name='revenue_per_audit',
            field=models.IntegerField(blank=True, db_column='revenue_per_audit', null=True),
        ),
    ]
