# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-23 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0014_auditcycle_revenue_per_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='hidden',
            field=models.BooleanField(db_column='hidden', default=False),
        ),
    ]
