# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0015_audit_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='audit_date',
            field=models.DateField(blank=True, db_column='audit_date', null=True),
        ),
    ]
