# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0017_auto_20180606_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='created_at',
            field=models.DateTimeField(db_column='created_at', null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='modified_at',
            field=models.DateTimeField(db_column='modified_at', null=True),
        ),
    ]
