# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_questionnairetype'),
        ('audit', '0018_auto_20180615_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcycle',
            name='questionnaire_type',
            field=models.ForeignKey(db_column='questionnaire_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='questionnaire.QuestionnaireType'),
        ),
    ]
