# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0019_auditcycle_questionnaire_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditcycle',
            name='description',
            field=models.CharField(db_column='description', max_length=16384),
        ),
        migrations.AlterField(
            model_name='auditcycle',
            name='post_approval_description',
            field=models.CharField(blank=True, db_column='post_approval_description', max_length=16384),
        ),
    ]
