# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-08 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0020_auto_20180906_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditcycle',
            name='status',
            field=models.CharField(choices=[('PREPARATION', 'Preparation'), ('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('REPORT', 'Report'), ('CLEARING', 'Clearing'), ('ARCHIVED', 'Archived')], db_column='status', max_length=20),
        ),
    ]
