# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-14 07:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0021_auto_20180908_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAttribute',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('json_id', models.CharField(db_column='json_id', max_length=20)),
                ('label', models.CharField(db_column='label', max_length=50)),
                ('attribute_data', django.contrib.postgres.fields.jsonb.JSONField(db_column='attribute_data', default={})),
                ('audit_cycle', models.ForeignKey(db_column='audit_cycle_id', on_delete=django.db.models.deletion.PROTECT, related_name='report_attributes', to='audit.AuditCycle')),
            ],
        ),
    ]
