# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-08 13:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0023_auto_20181014_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportattribute',
            name='attribute_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_column='attribute_data', default=dict),
        ),
    ]
