# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-12 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0024_auto_20190108_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcycle',
            name='check_points',
            field=models.CharField(blank=True, db_column='check_points', max_length=16384),
        ),
    ]
