# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-09 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_prooftag'),
        ('audit', '0025_auditcycle_check_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCycleProofTagList',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_at', models.DateTimeField(db_column='created_at', null=True)),
                ('audit_cycle', models.ForeignKey(db_column='audit_cycle_id', on_delete=django.db.models.deletion.PROTECT, related_name='proof_tags_list', to='audit.AuditCycle')),
                ('proof_tag', models.ForeignKey(db_column='proof_tag_id', on_delete=django.db.models.deletion.PROTECT, related_name='proof_tags_list', to='manager.ProofTag')),
            ],
        ),
    ]
