# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-02 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0026_auditcycleprooftaglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcycle',
            name='audit_auto_approve',
            field=models.BooleanField(db_column='audit_auto_approve', default=False),
        ),
    ]
