# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-15 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0027_auditcycle_audit_auto_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcycle',
            name='charge_per_audit',
            field=models.IntegerField(db_column='charge_per_audit', default=0),
        ),
        migrations.AddField(
            model_name='auditcycle',
            name='system_cost',
            field=models.IntegerField(db_column='system_cost', default=0),
        ),
    ]
