# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-27 06:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0028_auto_20210915_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcycle',
            name='planned_audit',
            field=models.IntegerField(db_column='planned_audit', default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
