# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-12-08 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0029_auditcycle_planned_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcycle',
            name='support_page_link',
            field=models.CharField(blank=True, db_column='support_page_link', max_length=200),
        ),
    ]
