# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-02-23 11:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0030_auditcycle_support_page_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcycle',
            name='audit_alignment_factors',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_column='audit_alignment_factors', default=dict),
        ),
    ]
