# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-03-24 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0032_auto_20220308_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcycle',
            name='created_by_client',
            field=models.BooleanField(db_column='created_by_client', default=False),
        ),
    ]
