# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-03-31 07:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0033_auditcycle_created_by_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditcycle',
            name='reimbursement',
            field=models.IntegerField(blank=True, db_column='reimbursement', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
