# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-07-04 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0030_store_pincode'),
        ('audit', '0034_auto_20220331_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcycle',
            name='quotation',
            field=models.ForeignKey(db_column='quotation_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_cycles', to='client.Quotation'),
        ),
    ]
