# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-07-15 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0031_auto_20220715_1038'),
        ('manager', '0019_city_tier'),
        ('audit', '0035_auditcycle_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(db_column='count')),
                ('audit_fee', models.DecimalField(db_column='audit_fee', decimal_places=1, max_digits=6)),
                ('city', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.PROTECT, to='manager.City')),
                ('quotation', models.ForeignKey(db_column='quotation_id', on_delete=django.db.models.deletion.PROTECT, related_name='audit_locations', to='client.Quotation')),
            ],
        ),
    ]
