# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-10 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0037_auditcycleprooftaglist_max_attachment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditcycleprooftaglist',
            name='audit_cycle',
            field=models.ForeignKey(db_column='audit_cycle_id', on_delete=django.db.models.deletion.PROTECT, related_name='solution_proof_tags_list', to='audit.AuditCycle'),
        ),
        migrations.AlterField(
            model_name='auditcycleprooftaglist',
            name='proof_tag',
            field=models.ForeignKey(db_column='proof_tag_id', on_delete=django.db.models.deletion.PROTECT, related_name='solution_proof_tags_list', to='manager.ProofTag'),
        ),
    ]
