# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-08-23 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0039_auto_20230710_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcycle',
            name='eligibility',
            field=models.CharField(blank=True, db_column='eligibility', max_length=16384),
        ),
    ]
