# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-08-31 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0049_auto_20230823_1114'),
        ('audit', '0040_auditcycle_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcycle',
            name='order_id',
            field=models.ForeignKey(blank=True, db_column='mporder_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='client.MPOrder'),
        ),
    ]
