# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-08-31 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0043_auto_20230831_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditcycle',
            name='order_id',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='client.MPOrder'),
        ),
    ]
