# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-09-04 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0044_auto_20230831_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditcycle',
            old_name='order_id',
            new_name='order',
        ),
    ]
