# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-09-26 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0045_auto_20230904_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditcycle',
            name='order',
            field=models.ForeignKey(db_column='order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.MPOrder'),
        ),
    ]
