# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-09-26 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0046_auto_20230926_1457'),
        ('audit', '0046_auto_20230926_1156'),
    ]

    operations = [
    ]
