# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-10-10 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0060_clientrequirements'),
        ('audit', '0047_merge_20230926_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcycle',
            name='clientrequirement',
            field=models.ForeignKey(blank=True, db_column='client_requirement_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='client.ClientRequirements'),
        ),
    ]
