# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-12-19 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0048_auditcycle_clientrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcycle',
            name='audit_report_summary',
            field=models.BooleanField(db_column='audit_report_summary', default=True),
        ),
    ]
