# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-01-24 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0049_auditcycle_audit_report_summary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='audit',
            unique_together=set([]),
        ),
    ]
