# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-05-06 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0050_auto_20250124_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcycle',
            name='audit_ai_autofill',
            field=models.BooleanField(db_column='audit_ai_autofill', default=False),
        ),
        migrations.AddField(
            model_name='auditcycle',
            name='audit_auto_fail',
            field=models.IntegerField(db_column='audit_auto_fail', default=2),
        ),
    ]
