# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-05-12 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0051_auto_20260506_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcycle',
            name='qa_ai_comparison',
            field=models.BooleanField(db_column='qa_ai_comparison', default=False),
        ),
    ]
