# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-06-12 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0052_auditcycle_qa_ai_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcycle',
            name='auditor_notes',
            field=models.CharField(blank=True, db_column='auditor_notes', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditcycle',
            name='type',
            field=models.CharField(choices=[('WALKIN', 'Walkin'), ('PHONE', 'Phone'), ('WEB', 'Web'), ('VISIBILITY', 'Visibility'), ('COMPETITION', 'Competition'), ('SERVICE', 'Service'), ('AT_HOME', 'At Home'), ('SALES', 'Sales'), ('FINE_DINE', 'Fine Dine'), ('SKY_KARTING', 'Sky Karting'), ('SMAAASH_ARENA', 'Smaaash Arena'), ('GENERAL', 'General'), ('SMAAASH', 'Smaaash'), ('SMAAASH_MEGA', 'Smaaash Mega'), ('SMAAASH_ZONE', 'Smaaash Zone'), ('DDC', 'Ddc'), ('HTC', 'Htc'), ('ASCVD', 'Ascvd'), ('SKIN_HYDRATION', 'Skin Hydration'), ('HYPER_PIGMENTATION', 'Hyper Pigmentation'), ('SKIN_SENSITIVE', 'Skin Sensitive'), ('RETAIL', 'Retail')], db_column='type', max_length=20),
        ),
    ]
