# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-06-26 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0067_clientmoderator'),
        ('audit', '0053_auto_20260612_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='trainer',
            field=models.ForeignKey(blank=True, db_column='client_trainer_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='client.ClientTrainer'),
        ),
    ]
