# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-06-29 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0054_audit_trainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='trainer',
            new_name='client_trainer',
        ),
    ]
