# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-06-29 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0055_auto_20260629_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcycle',
            name='pm_review_bypass',
            field=models.BooleanField(db_column='pm_review_bypass', default=False),
        ),
    ]
