# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-28 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0003_auto_20170127_1934'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditStore',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_column='status', max_length=20)),
                ('audit_date', models.DateField(db_column='audit_date')),
                ('audit', models.ForeignKey(db_column='audit_id', on_delete=django.db.models.deletion.CASCADE, to='audit.Audit')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
