# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-05 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0002_auto_20170203_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditstore',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('FAILED', 'Failed'), ('SUBMITTED', 'Submitted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_column='status', max_length=20),
        ),
    ]
