# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-05 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0004_auto_20170205_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditstore',
            name='audit',
            field=models.ForeignKey(db_column='audit_id', on_delete=django.db.models.deletion.CASCADE, related_name='audit_stores', to='audit.Audit'),
        ),
    ]
