# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0005_auto_20170205_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditstore',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('FAILED', 'Failed'), ('SUBMITTED', 'Submitted'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_column='status', max_length=20),
        ),
    ]
