# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0006_auto_20170622_0725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditstore',
            options={'permissions': (('clientuser_visible', 'ClientUser can view this AuditStore instance'),)},
        ),
    ]
