# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0007_auto_20170720_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditstore',
            name='audit',
            field=models.ForeignKey(db_column='audit_id', on_delete=django.db.models.deletion.PROTECT, related_name='audit_stores', to='audit.Audit'),
        ),
        migrations.AlterField(
            model_name='auditstore',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
