# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-12 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0009_auto_20171010_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstore',
            name='qa_rating',
            field=models.IntegerField(choices=[(0, 'Bad'), (1, 'Average'), (2, 'Good')], db_column='qa_rating', null=True),
        ),
    ]
