# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-12 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0010_auditstore_qa_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditstore',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('FAILED', 'Failed'), ('ACKNOWLEDGED', 'Acknowledged'), ('SUBMITTED', 'Submitted'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_column='status', max_length=20),
        ),
    ]
