# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-29 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0011_auto_20180112_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditstore',
            options={'permissions': (('clientuser_visible', 'ClientUser can view this AuditStore instance'), ('moderator_manage', 'Moderator can manage this AuditStore instance'))},
        ),
    ]
