# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0012_auto_20180129_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditstore',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('FAILED', 'Failed'), ('ACKNOWLEDGED', 'Acknowledged'), ('SUBMITTED', 'Submitted'), ('PM_REVIEW', 'PM Review'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_column='status', max_length=20),
        ),
    ]
