# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 13:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit_store', '0013_auto_20180527_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStatusLog',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('status', models.CharField(db_column='status', max_length=20)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('audit_store', models.ForeignKey(db_column='audit_store_id', on_delete=django.db.models.deletion.PROTECT, to='audit_store.AuditStore')),
                ('user_actor', models.ForeignKey(db_column='user_actor_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
