# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0014_reportstatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstore',
            name='earnings_per_audit',
            field=models.IntegerField(db_column='earnings_per_audit', null=True),
        ),
        migrations.AddField(
            model_name='auditstore',
            name='reimbursement',
            field=models.IntegerField(db_column='reimbursement', null=True),
        ),
    ]
