# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 17:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0015_auto_20180902_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstore',
            name='attribute_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_column='attribute_data', default=dict),
        ),
    ]
