# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-02 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0016_auditstore_attribute_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportstatuslog',
            name='message',
            field=models.CharField(blank=True, db_column='message', max_length=4096, null=True),
        ),
    ]
