# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0016_auditstore_attribute_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstore',
            name='report_summary',
            field=models.CharField(blank=True, db_column='report_summary', max_length=16384),
        ),
        migrations.AddField(
            model_name='auditstore',
            name='report_summary_original',
            field=models.CharField(blank=True, db_column='report_summary_original', max_length=16384),
        ),
    ]
