# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-01 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0018_reportstatuslog_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstore',
            name='moderator_comment',
            field=models.CharField(blank=True, db_column='moderator_comment', max_length=3000),
        ),
        migrations.AddField(
            model_name='auditstore',
            name='moderator_status',
            field=models.CharField(blank=True, choices=[('MISS_IMAGE', 'Missing Image'), ('MISS_AUDIO', 'Missing Audio'), ('MISS_AUDIO', 'Missing Video'), ('AUDITOR_NOT_RESPONDING', 'Auditor Not Responding'), ('CONTRADICTION', 'Contradiction'), ('NOT_SUFFICIENT_PROOFS', 'Not Suffiecient Proofs'), ('DATE_TIME_MISSING', 'Date or Time Missing in Image'), ('WAITING_FOR_ATTACHMENT', 'Waiting for Attachment from Auditor'), ('FAULTY_REPORT', 'Faulty Report')], db_column='moderator_status', max_length=100),
        ),
    ]
