# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-12 11:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0019_auto_20191001_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstore',
            name='check_points',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_column='check_points', default=dict),
        ),
    ]
