# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-10 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0020_auditstore_check_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditstore',
            name='moderator_status',
            field=models.CharField(blank=True, choices=[('MISS_IMAGE', 'Missing Image'), ('MISS_AUDIO', 'Missing Audio'), ('MISS_AUDIO', 'Missing Video'), ('AUDITOR_NOT_RESPONDING', 'Auditor Not Responding'), ('CONTRADICTION', 'Contradiction'), ('NOT_SUFFICIENT_PROOFS', 'Not Sufficient Proofs'), ('DATE_TIME_MISSING', 'Date or Time Missing in Image'), ('WAITING_FOR_ATTACHMENT', 'Waiting for Attachment from Auditor'), ('FAULTY_REPORT', 'Faulty Report')], db_column='moderator_status', max_length=100),
        ),
    ]
