# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-10 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0021_auto_20200110_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstore',
            name='audit_store_percentage',
            field=models.IntegerField(blank=True, db_column='percentage', null=True),
        ),
    ]
