# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-26 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0022_auditstore_audit_store_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditstore',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('FAILED', 'Failed'), ('ACKNOWLEDGED', 'Acknowledged'), ('SUBMITTED', 'Submitted'), ('PM_REVIEW', 'PM Review'), ('COMPLETED', 'Completed'), ('AUDITOR_WITHDRAWN', 'Auditor Withdrawn'), ('WITHDRAWN', 'Withdrawn'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_column='status', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportstatuslog',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('FAILED', 'Failed'), ('ACKNOWLEDGED', 'Acknowledged'), ('SUBMITTED', 'Submitted'), ('PM_REVIEW', 'PM Review'), ('COMPLETED', 'Completed'), ('AUDITOR_WITHDRAWN', 'Auditor Withdrawn'), ('WITHDRAWN', 'Withdrawn'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_column='status', max_length=20),
        ),
    ]
