# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-04 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0023_auto_20200326_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportActionPlan',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('action_plan_description', models.CharField(blank=True, db_column='action_plan_description', max_length=4096, null=True)),
                ('person_responsible', models.CharField(blank=True, db_column='person_responsible', max_length=100, null=True)),
                ('target_date', models.DateField(db_column='target_date')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('TAKEN', 'TAKEN')], db_column='status', max_length=20)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('modified_at', models.DateTimeField(db_column='modified_at')),
                ('audit_store', models.ForeignKey(db_column='audit_store_id', on_delete=django.db.models.deletion.PROTECT, to='audit_store.AuditStore')),
            ],
        ),
    ]
