# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-10 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0024_reportactionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportactionplan',
            name='created_by',
            field=models.CharField(blank=True, db_column='created_by', max_length=100, null=True),
        ),
    ]
