# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-11-23 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0025_reportactionplan_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstore',
            name='submit_at',
            field=models.DateTimeField(db_column='submit_at', null=True),
        ),
    ]
