# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-17 12:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit_store', '0026_auditstore_submit_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConcernLog',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, db_column='message', max_length=4096, null=True)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('audit_store', models.ForeignKey(db_column='audit_store_id', on_delete=django.db.models.deletion.PROTECT, to='audit_store.AuditStore')),
                ('user_actor', models.ForeignKey(db_column='user_actor_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
