# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-02-08 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit_store', '0027_reportconcernlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFollowUpLog',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('comment', models.CharField(db_column='comment', max_length=4096)),
                ('next_follow_up_date', models.DateTimeField(db_column='next_follow_up_date', null=True)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('modified_at', models.DateTimeField(db_column='modified_at')),
                ('audit_store', models.ForeignKey(db_column='audit_store_id', on_delete=django.db.models.deletion.PROTECT, related_name='follow_up', to='audit_store.AuditStore')),
                ('user_actor', models.ForeignKey(db_column='user_actor_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
