# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-03-03 06:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0028_reportfollowuplog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportstatuslog',
            options={'get_latest_by': 'id'},
        ),
        migrations.AddField(
            model_name='reportstatuslog',
            name='report_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_column='report_data', default=dict),
        ),
        migrations.AlterField(
            model_name='reportstatuslog',
            name='audit_store',
            field=models.ForeignKey(db_column='audit_store_id', on_delete=django.db.models.deletion.PROTECT, related_name='audit_store_status_log', to='audit_store.AuditStore'),
        ),
    ]
