# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-03-09 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0029_auto_20220303_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstore',
            name='auto_assigned',
            field=models.BooleanField(db_column='auto_assigned', default=False),
        ),
    ]
