# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-04-27 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0030_auditstore_auto_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstore',
            name='report_revert_count',
            field=models.IntegerField(blank=True, db_column='report_revert_count', default=0, null=True),
        ),
    ]
