# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-10-03 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0031_auditstore_report_revert_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstore',
            name='instant_assigned',
            field=models.BooleanField(db_column='instant_assigned', default=False),
        ),
    ]
