# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-04-18 05:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit_store', '0032_auditstore_instant_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFeedbackByAuditor',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('audit_understanding', models.CharField(blank=True, db_column='audit_understanding', max_length=4096, null=True)),
                ('coordination', models.CharField(blank=True, db_column='coordination', max_length=4096, null=True)),
                ('portal_accessibility', models.CharField(blank=True, db_column='portal_accessibility', max_length=4096, null=True)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('audit_store', models.ForeignKey(db_column='audit_store_id', on_delete=django.db.models.deletion.PROTECT, to='audit_store.AuditStore')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
