# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-04-23 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0033_reportfeedbackbyauditor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfeedbackbyauditor',
            name='audit_understanding',
            field=models.PositiveSmallIntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], db_column='audit_understanding', default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportfeedbackbyauditor',
            name='coordination',
            field=models.PositiveSmallIntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], db_column='coordination', default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportfeedbackbyauditor',
            name='portal_accessibility',
            field=models.CharField(blank=True, db_column='portal_accessibility', max_length=5096, null=True),
        ),
    ]
