# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-05-16 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0034_auto_20240423_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstore',
            name='sentiment_score',
            field=models.FloatField(blank=True, db_column='sentiment_score', null=True),
        ),
        migrations.AddField(
            model_name='auditstore',
            name='sentiment_text',
            field=models.CharField(blank=True, db_column='sentiment_text', max_length=100, null=True),
        ),
    ]
