# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-05-16 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0035_auto_20240516_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditstore',
            name='audit_date',
            field=models.DateField(db_column='audit_date', null=True),
        ),
    ]
