# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-06-12 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0037_auto_20240530_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditstore',
            name='sentiment_text',
        ),
        migrations.AddField(
            model_name='auditstore',
            name='sentiment_bullet_points',
            field=models.CharField(blank=True, db_column='bullet_points', max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='auditstore',
            name='sentiment_emotions',
            field=models.CharField(blank=True, db_column='emotions', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='auditstore',
            name='sentiment_main_keywords',
            field=models.CharField(blank=True, db_column='main_keywords', max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='auditstore',
            name='sentiment_negative_words',
            field=models.CharField(blank=True, db_column='negative_words', max_length=30000, null=True),
        ),
        migrations.AddField(
            model_name='auditstore',
            name='sentiment_positive_words',
            field=models.CharField(blank=True, db_column='positive_words', max_length=30000, null=True),
        ),
        migrations.AddField(
            model_name='auditstore',
            name='sentiment_socre_result',
            field=models.CharField(blank=True, db_column='sentiment_socre_result', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditstore',
            name='sentiment_score',
            field=models.CharField(blank=True, db_column='sentiment_score', max_length=50, null=True),
        ),
    ]
