# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-06-12 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0038_auto_20240612_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditstore',
            old_name='sentiment_socre_result',
            new_name='sentiment_score_result',
        ),
    ]
