# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-06-12 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0039_auto_20240612_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditstore',
            old_name='sentiment_score_result',
            new_name='sentiment_text',
        ),
    ]
