# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-06-12 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0040_auto_20240612_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditstore',
            name='sentiment_text',
            field=models.CharField(blank=True, db_column='sentiment_text', max_length=50, null=True),
        ),
    ]
