# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-06-13 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0041_auto_20240612_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditstore',
            name='sentiment_bullet_points',
        ),
        migrations.RemoveField(
            model_name='auditstore',
            name='sentiment_emotions',
        ),
        migrations.RemoveField(
            model_name='auditstore',
            name='sentiment_main_keywords',
        ),
        migrations.RemoveField(
            model_name='auditstore',
            name='sentiment_negative_words',
        ),
        migrations.RemoveField(
            model_name='auditstore',
            name='sentiment_positive_words',
        ),
    ]
