# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-06-14 05:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0042_auto_20240613_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstore',
            name='bullet_points',
            field=models.CharField(blank=True, db_column='bullet_points', max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='auditstore',
            name='main_keywords',
            field=models.CharField(blank=True, db_column='main_keywords', max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='auditstore',
            name='sentiment_emotions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='sentiment_emotions', null=True),
        ),
        migrations.AddField(
            model_name='auditstore',
            name='sentiment_negative_words',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='sentiment_negative_words', null=True),
        ),
        migrations.AddField(
            model_name='auditstore',
            name='sentiment_positive_words',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='sentiment_positive_words', null=True),
        ),
    ]
