# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-06-14 09:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0043_auto_20240614_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditstore',
            name='bullet_points',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='bullet_points', null=True),
        ),
        migrations.AlterField(
            model_name='auditstore',
            name='main_keywords',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='main_keywords', null=True),
        ),
    ]
