# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-08-30 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0044_auto_20240614_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstore',
            name='nps_section',
            field=models.CharField(blank=True, db_column='nps_section', max_length=16384, null=True),
        ),
    ]
