# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-09-02 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0045_auditstore_nps_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditstore',
            name='nps_section',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 10), (9, 9), (8, 8), (7, 7), (6, 6), (5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], db_column='nps_section', null=True),
        ),
    ]
