# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-04-14 10:32
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0046_auto_20240902_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstore',
            name='qa_rating_feedback',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, db_column='qa_rating_feedback', null=True, size=None),
        ),
    ]
