# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-05-30 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0048_auditstore_report_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditstore',
            name='report_time',
        ),
        migrations.AddField(
            model_name='auditstore',
            name='report_submission_time',
            field=models.CharField(blank=True, db_column='report_submission_time', max_length=50, null=True),
        ),
    ]
