# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-06-02 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0049_auto_20250530_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstore',
            name='moderator_submission_time',
            field=models.CharField(blank=True, db_column='moderator_submission_time', max_length=50, null=True),
        ),
    ]
