# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-07-03 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0050_auditstore_moderator_submission_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstore',
            name='moderator_submission_date',
            field=models.DateTimeField(blank=True, db_column='moderator_submission_date', null=True),
        ),
    ]
