# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-07-09 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0051_auditstore_moderator_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstore',
            name='report_summary_old',
            field=models.CharField(blank=True, db_column='report_summary_old', max_length=66384, null=True),
        ),
    ]
