# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-09-09 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0052_auditstore_report_summary_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstore',
            name='failed_by',
            field=models.CharField(blank=True, choices=[('System', 'System'), ('Manual', 'Manual')], db_column='failed_by', max_length=120, null=True),
        ),
    ]
