# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-09-22 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0053_auditstore_failed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditstore',
            name='failed_by',
            field=models.CharField(blank=True, choices=[('SYSTEM', 'System'), ('MANUAL', 'Manual')], db_column='failed_by', max_length=120, null=True),
        ),
    ]
