# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-04-09 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0054_auto_20250922_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstore',
            name='submission_source',
            field=models.CharField(blank=True, db_column='submission_source', max_length=120, null=True),
        ),
    ]
