# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-05-06 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0055_auditstore_submission_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstore',
            name='report_completion_percentage',
            field=models.IntegerField(db_column='report_completion_percentage', default=0),
        ),
    ]
