# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-05-07 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0056_auditstore_report_completion_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditstore',
            name='report_completion_percentage',
            field=models.IntegerField(blank=True, db_column='report_completion_percentage', null=True),
        ),
    ]
