# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-06-24 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_store', '0057_auto_20260507_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditstore',
            name='assigned_by',
            field=models.CharField(blank=True, db_column='assigned_by', max_length=120, null=True),
        ),
    ]
