# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.TextField(db_column=b'bank_name', max_length=b'40')),
                ('account_holder_name', models.TextField(db_column=b'account_holder_name', max_length=b'40')),
                ('account_number', models.TextField(db_column=b'account_number', max_length=b'20')),
                ('ifsc_code', models.TextField(db_column=b'ifsc_code', max_length=b'20')),
                ('user', models.ForeignKey(db_column=b'user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.TextField(db_column=b'mobile_number', max_length=b'15')),
                ('date_of_birth', models.DateField(db_column=b'dob')),
                ('address', models.TextField(db_column=b'address', max_length=b'100')),
                ('pincode', models.TextField(db_column=b'pincode', max_length=b'10')),
                ('city', models.TextField(db_column=b'city', max_length=b'20')),
                ('state', models.TextField(db_column=b'state', max_length=b'20')),
                ('user', models.ForeignKey(db_column=b'user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
