# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poseidon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_car', models.BooleanField(db_column=b'has_car')),
                ('weekend_audit', models.BooleanField(db_column=b'weekend_audit')),
                ('user', models.ForeignKey(db_column=b'user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='education',
            field=models.CharField(choices=[(b'TE', b'tenth'), (b'TW', b'twelvth'), (b'CO', b'college'), (b'GR', b'graduate'), (b'PG', b'post_graduate'), (b'OT', b'other')], db_column=b'education', default='TE', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='gender',
            field=models.CharField(choices=[(b'M', b'male'), (b'F', b'female')], db_column=b'gender', default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='marital_status',
            field=models.CharField(choices=[(b'SI', b'single'), (b'MA', b'married'), (b'SE', b'separated')], db_column=b'marital_status', default='SI', max_length=2),
            preserve_default=False,
        ),
    ]
