# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('sent_to', models.EmailField(db_column='sent_to', max_length=254)),
                ('subject', models.CharField(db_column='name', max_length=128)),
                ('html_body', models.TextField(db_column='html_body')),
                ('text_body', models.TextField(db_column='text_body')),
                ('sent_at', models.DateTimeField(db_column='sent_at')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
