# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-18 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('sent_to', models.CharField(db_column='mobile_number', max_length=10)),
                ('message_status', models.CharField(db_column='message_status', max_length=50)),
                ('sent_at', models.DateTimeField(db_column='sent_at')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
