# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-10 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_messagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_to', models.CharField(db_column='whatsapp_number', max_length=10)),
                ('communication_id', models.CharField(db_column='communication_id', max_length=200)),
                ('message_id', models.CharField(db_column='message_id', max_length=200)),
                ('sent_at', models.DateTimeField(db_column='sent_at')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
