# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-01-19 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_whatsapplog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(db_column='name', max_length=200),
        ),
    ]
