# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('file_slug', models.CharField(db_column='file_slug', max_length=200)),
                ('proof_type', models.CharField(db_column='proof_type', max_length=20)),
                ('mime_type', models.CharField(db_column='mime_type', max_length=20)),
                ('file_name', models.CharField(db_column='file_name', max_length=40)),
                ('status', models.CharField(choices=[('ATTACHED', 'Attached'), ('DELETED', 'Deleted')], db_column='status', max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
