# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_name',
            field=models.CharField(db_column='file_name', max_length=256),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='mime_type',
            field=models.CharField(db_column='mime_type', max_length=50),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='proof_type',
            field=models.CharField(choices=[('PHOTO', 'Photo'), ('AUDIO', 'Audio'), ('AUDIO', 'Video')], db_column='proof_type', max_length=20),
        ),
    ]
