# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0002_auto_20170214_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_size',
            field=models.IntegerField(db_column='file_size', default=0),
            preserve_default=False,
        ),
    ]
