# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-30 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0003_attachment_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='proof_type',
            field=models.CharField(choices=[('PHOTO', 'Photo'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('ID_PROOF', 'ID Proof')], db_column='proof_type', max_length=20),
        ),
    ]
