# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-05 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0004_auto_20170730_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='mime_type',
            field=models.CharField(db_column='mime_type', max_length=256),
        ),
    ]
