# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-26 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0007_auto_20171010_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='status',
            field=models.CharField(choices=[('UPLOADING', 'Uploading'), ('ATTACHED', 'Attached'), ('DELETED', 'Deleted')], db_column='status', max_length=20),
        ),
    ]
