# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-09 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0008_auto_20180226_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='attachment_id',
            field=models.CharField(blank=True, db_column='attachment_id', max_length=50),
        ),
        migrations.AddField(
            model_name='attachment',
            name='image_hash',
            field=models.CharField(blank=True, db_column='image_hash', max_length=500),
        ),
    ]
