# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-11 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0026_auditcycleprooftaglist'),
        ('attachment', '0009_auto_20191009_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='proof_tag',
            field=models.ForeignKey(blank=True, db_column='proof_tag', default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='audit.AuditCycleProofTagList'),
        ),
    ]
