# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-30 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0010_attachment_proof_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='proof_tag',
            field=models.ForeignKey(blank=True, db_column='proof_tag_id', default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='audit.AuditCycleProofTagList'),
        ),
    ]
