# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-29 07:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0011_auto_20200430_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='extra_properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_column='extra_properties', default=dict),
        ),
    ]
