# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-26 08:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0012_attachment_extra_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='audio_transcript_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_column='audio_transcript_data', default=dict),
        ),
    ]
