# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-10-18 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0013_attachment_audio_transcript_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='bucket',
            field=models.CharField(choices=[('BUCKET', 'BUCKET'), ('GUIDELINE_BUCKET', 'GUIDELINE_BUCKET')], db_column='bucket', default='BUCKET', max_length=20),
        ),
    ]