# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-10-19 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0014_attachment_bucket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='bucket',
        ),
    ]
