# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-07-03 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0016_attachment_old_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='old_file_name',
            field=models.CharField(blank=True, db_column='old_file_name', default='', max_length=256, null=True),
        ),
    ]
