# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-04-27 08:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0017_auto_20250703_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='audio_to_text_clean',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='audio_to_text_clean', default=dict, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='audio_to_text_row',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='audio_to_text_row', default=dict, null=True),
        ),
    ]
