# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-06-26 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0018_auto_20260427_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='attachment_category',
            field=models.CharField(blank=True, choices=[('GUIDELINE', 'Guideline'), ('REFERENCE_ATTACHMENT', 'Reference Attachment'), ('AUDIT_STORE', 'Audit Store')], db_column='attachment_category', max_length=20, null=True),
        ),
    ]
