# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-06-26 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0019_attachment_attachment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='link_url',
            field=models.CharField(blank=True, db_column='link_url', max_length=3000, null=True),
        ),
    ]
