# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-08-10 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0020_attachment_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='attachment_comment',
            field=models.TextField(blank=True, db_column='attachment_comment', null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='is_edited',
            field=models.BooleanField(db_column='is_edited', default=False),
        ),
        migrations.AddField(
            model_name='attachment',
            name='original_attachment',
            field=models.ForeignKey(blank=True, db_column='original_attachment_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edited_attachments', to='attachment.Attachment'),
        ),
    ]
