# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 13:16
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('facebook_id', models.CharField(blank=True, db_column='facebook_id', max_length=64, null=True)),
                ('access_token', models.CharField(blank=True, db_column='access_token', max_length=1024, null=True)),
                ('profile_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='profile_data', default={}, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(db_column='is_verified', default=False)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
