# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-03 09:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20171113_1326'),
        ('social', '0002_auto_20171128_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterFeed',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('tweet_id', models.CharField(db_column='tweet_id', max_length=100, unique=True)),
                ('tweet_text', models.CharField(db_column='tweet_text', max_length=1024)),
                ('tweet_created_on', models.DateTimeField()),
                ('sentiment_score', models.FloatField(db_column='sentiment_score')),
                ('sentiment_text', models.CharField(db_column='sentiment_text', max_length=100)),
                ('tweet_data', django.contrib.postgres.fields.jsonb.JSONField(db_column='tweet_data', default={})),
            ],
        ),
        migrations.CreateModel(
            name='TwitterHandle',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('twitter_handle', models.CharField(db_column='twitter_handle', max_length=100)),
                ('is_enabled', models.BooleanField(db_column='is_enabled', default=False)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='twitter_handle', to='client.Client')),
            ],
        ),
        migrations.AddField(
            model_name='twitterfeed',
            name='twitter_handle',
            field=models.ForeignKey(db_column='twitter_handle_id', on_delete=django.db.models.deletion.PROTECT, related_name='twitter_feeds', to='social.TwitterHandle'),
        ),
        migrations.AlterUniqueTogether(
            name='twitterhandle',
            unique_together=set([('client', 'twitter_handle')]),
        ),
    ]
