# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 17:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20171203_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook',
            name='profile_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='profile_data', default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='twitterfeed',
            name='tweet_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_column='tweet_data', default=dict),
        ),
    ]
