
export const FETCH_AUDIT_STORE = "FETCH_AUDIT_STORE";
export const FETCH_SECTIONS = "FETCH_SECTIONS";
export const FETCH_ANSWERS = "FETCH_ANSWERS";
export const FETCH_ANSWER = "FETCH_ANSWER";
export const FETCH_REPORT_SECTIONS = "FETCH_REPORT_SECTIONS";
export const FETCH_REPORT_SECTION = "FETCH_REPORT_SECTION";
