# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 19:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0011_auto_20170829_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50)),
                ('formed_in_year', models.IntegerField(blank=True, db_column='formed_in_year', null=True)),
                ('gstin', models.CharField(blank=True, db_column='gstin', max_length=15)),
                ('cin', models.CharField(blank=True, db_column='cin', max_length=21)),
                ('agreement_accepted', models.BooleanField(db_column='agreement_accepted', default=False)),
                ('strength', models.IntegerField(blank=True, db_column='strength', null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgencyPresence',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('present', models.BooleanField(db_column='present', default=False)),
                ('agency', models.ForeignKey(db_column='agency_id', on_delete=django.db.models.deletion.PROTECT, related_name='presences', to='agency.Agency')),
                ('city', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.PROTECT, to='manager.City')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyUser',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_column='full_name', max_length=50)),
                ('agency', models.ForeignKey(db_column='agency_id', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='agency.Agency')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='agencypresence',
            unique_together=set([('city', 'agency')]),
        ),
    ]
