# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='account_holder_name',
            field=models.CharField(blank=True, db_column='account_holder_name', max_length=40),
        ),
        migrations.AddField(
            model_name='agency',
            name='account_number',
            field=models.CharField(blank=True, db_column='account_number', max_length=20),
        ),
        migrations.AddField(
            model_name='agency',
            name='ifsc_code',
            field=models.CharField(blank=True, db_column='ifsc_code', max_length=20),
        ),
    ]
