# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-09 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0011_auto_20170829_1043'),
        ('audit', '0013_auto_20170829_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityEmailRecord',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('total_count', models.PositiveIntegerField(db_column='total_count')),
                ('progress_count', models.PositiveIntegerField(db_column='progress_count', default=0)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('modified_at', models.DateTimeField(db_column='modified_at')),
                ('audit_cycle', models.ForeignKey(db_column='audit_cycle_id', on_delete=django.db.models.deletion.PROTECT, to='audit.AuditCycle')),
                ('city', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.PROTECT, to='manager.City')),
            ],
        ),
    ]
