# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-13 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunityemailrecord',
            options={'ordering': ['-created_at']},
        ),
    ]
