# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-02-16 09:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_auto_20171113_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunityemailrecord',
            name='record_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_column='record_data', default=dict),
        ),
    ]
