# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-05-24 09:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_city_tier'),
        ('audit', '0034_auto_20220331_0719'),
        ('notify', '0003_opportunityemailrecord_record_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunitySmsRecord',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('total_count', models.PositiveIntegerField(db_column='total_count')),
                ('progress_count', models.PositiveIntegerField(db_column='progress_count', default=0)),
                ('record_data', django.contrib.postgres.fields.jsonb.JSONField(db_column='record_data', default=dict)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('modified_at', models.DateTimeField(db_column='modified_at')),
                ('audit_cycle', models.ForeignKey(db_column='audit_cycle_id', on_delete=django.db.models.deletion.PROTECT, to='audit.AuditCycle')),
                ('city', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.PROTECT, to='manager.City')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityWhatsappRecord',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('total_count', models.PositiveIntegerField(db_column='total_count')),
                ('progress_count', models.PositiveIntegerField(db_column='progress_count', default=0)),
                ('record_data', django.contrib.postgres.fields.jsonb.JSONField(db_column='record_data', default=dict)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('modified_at', models.DateTimeField(db_column='modified_at')),
                ('audit_cycle', models.ForeignKey(db_column='audit_cycle_id', on_delete=django.db.models.deletion.PROTECT, to='audit.AuditCycle')),
                ('city', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.PROTECT, to='manager.City')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
