# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-02-03 08:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_opportunitysmsrecord_opportunitywhatsapprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunityemailrecord',
            name='email_status',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='email_status', default=dict),
        ),
    ]
