# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-02-03 08:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_opportunityemailrecord_email_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunityemailrecord',
            name='email_status',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='email_status', default=dict, null=True),
        ),
    ]
