# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 16:36
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'walkin'), (2, 'phone'), (3, 'web'), (4, 'visibility'), (5, 'competition')], db_column='type')),
                ('status', models.IntegerField(choices=[(1, 'upcoming'), (2, 'active'), (3, 'archived')], db_column='status')),
                ('startDate', models.DateField(db_column='start_date')),
                ('endDate', models.DateField(db_column='end_date')),
                ('description', models.CharField(db_column='description', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLocation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('count', models.IntegerField(db_column='count')),
                ('audit', models.ForeignKey(db_column='audit_id', on_delete=django.db.models.deletion.CASCADE, to='manager.Audit')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=50)),
                ('email', models.EmailField(db_column='email', max_length=50)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('pincode', models.CharField(db_column='pincode', max_length=6)),
                ('city', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.CASCADE, to='manager.City')),
            ],
        ),
        migrations.AddField(
            model_name='auditlocation',
            name='auditLocation',
            field=models.ForeignKey(db_column='audit_location_id', on_delete=django.db.models.deletion.CASCADE, to='manager.Location'),
        ),
        migrations.AddField(
            model_name='audit',
            name='client',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, to='manager.Client'),
        ),
    ]
