# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20161014_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='client',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='manager.Client'),
        ),
        migrations.AlterField(
            model_name='auditlocation',
            name='audit',
            field=models.ForeignKey(db_column='audit_id', on_delete=django.db.models.deletion.CASCADE, related_name='auditlocations', to='manager.Audit'),
        ),
        migrations.AlterField(
            model_name='auditlocation',
            name='count',
            field=models.PositiveIntegerField(db_column='count'),
        ),
        migrations.AlterField(
            model_name='auditlocation',
            name='location',
            field=models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, related_name='auditlocations', to='manager.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='manager.City'),
        ),
    ]
