# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20161021_1102'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='auditlocation',
            unique_together=set([('location', 'audit')]),
        ),
    ]
