# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20161025_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.CharField(db_column='state', default='IN-MH', max_length=5),
            preserve_default=False,
        ),
    ]
