# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20161117_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='earnings_per_audit',
            field=models.IntegerField(db_column='earnings_per_audit', default=0),
            preserve_default=False,
        ),
    ]
