# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0016_auto_20170124_0828'),
        ('manager', '0007_audit_earnings_per_audit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='client',
        ),
        migrations.AlterUniqueTogether(
            name='auditlocation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='auditlocation',
            name='audit',
        ),
        migrations.RemoveField(
            model_name='auditlocation',
            name='location',
        ),
        migrations.DeleteModel(
            name='Audit',
        ),
        migrations.DeleteModel(
            name='AuditLocation',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
