# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-29 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20170312_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='manager.City'),
        ),
    ]
