# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-09 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20170829_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofTag',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('description', models.CharField(blank=True, db_column='description', max_length=1000)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_at', models.DateTimeField(db_column='created_at', null=True)),
                ('modified_at', models.DateTimeField(db_column='modified_at', null=True)),
            ],
        ),
    ]
