# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-24 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_prooftag'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(choices=[('IN', 'India'), ('AU', 'Australia')], db_column='country', default='IN', max_length=5),
        ),
    ]
