# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-25 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(choices=[('AU', 'Australia'), ('IN', 'India'), ('NZ', 'New Zealand'), ('UK', 'United Kingdom')], db_column='country', default='IN', max_length=5),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.CharField(choices=[('IN-AN', 'Andaman and Nicobar Islands'), ('IN-AP', 'Andhra Pradesh'), ('IN-AR', 'Arunachal Pradesh'), ('IN-AS', 'Assam'), ('IN-BR', 'Bihar'), ('IN-CH', 'Chandigarh'), ('IN-CT', 'Chhattisgarh'), ('IN-DN', 'Dadra and Nagar Haveli'), ('IN-DD', 'Daman and Diu'), ('IN-DL', 'Delhi'), ('IN-GA', 'Goa'), ('IN-GJ', 'Gujarat'), ('IN-HR', 'Haryana'), ('IN-HP', 'Himachal Pradesh'), ('IN-JK', 'Jammu and Kashmir'), ('IN-JH', 'Jharkhand'), ('IN-KA', 'Karnataka'), ('IN-KL', 'Kerala'), ('IN-LD', 'Lakshadweep'), ('IN-MP', 'Madhya Pradesh'), ('IN-MH', 'Maharashtra'), ('IN-MN', 'Manipur'), ('IN-ML', 'Meghalaya'), ('IN-MZ', 'Mizoram'), ('IN-NL', 'Nagaland'), ('IN-OR', 'Odisha'), ('IN-PB', 'Punjab'), ('IN-PY', 'Puducherry'), ('IN-RJ', 'Rajasthan'), ('IN-SK', 'Sikkim'), ('IN-TN', 'Tamil Nadu'), ('IN-TG', 'Telangana'), ('IN-TR', 'Tripura'), ('IN-UT', 'Uttarakhand'), ('IN-UP', 'Uttar Pradesh'), ('IN-WB', 'West Bengal'), ('AU-NS', 'New South Wales'), ('AU-NT', 'Northern Territory'), ('AU-QL', 'Queensland'), ('AU-TA', 'Tasmania'), ('AU-VI', 'Victoria'), ('AU-WA', 'Western Australia')], db_column='state', max_length=5),
        ),
    ]
