# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-26 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_auto_20200925_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(choices=[('AU', 'Australia'), ('EN', 'England'), ('IN', 'India'), ('NZ', 'New Zealand'), ('SG', 'Singapore'), ('US', 'United States')], db_column='country', default='IN', max_length=5),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.CharField(choices=[('IN-AN', 'Andaman and Nicobar Islands'), ('IN-AP', 'Andhra Pradesh'), ('IN-AR', 'Arunachal Pradesh'), ('IN-AS', 'Assam'), ('IN-BR', 'Bihar'), ('IN-CH', 'Chandigarh'), ('IN-CT', 'Chhattisgarh'), ('IN-DN', 'Dadra and Nagar Haveli'), ('IN-DD', 'Daman and Diu'), ('IN-DL', 'Delhi'), ('IN-GA', 'Goa'), ('IN-GJ', 'Gujarat'), ('IN-HR', 'Haryana'), ('IN-HP', 'Himachal Pradesh'), ('IN-JK', 'Jammu and Kashmir'), ('IN-JH', 'Jharkhand'), ('IN-KA', 'Karnataka'), ('IN-KL', 'Kerala'), ('IN-LD', 'Lakshadweep'), ('IN-MP', 'Madhya Pradesh'), ('IN-MH', 'Maharashtra'), ('IN-MN', 'Manipur'), ('IN-ML', 'Meghalaya'), ('IN-MZ', 'Mizoram'), ('IN-NL', 'Nagaland'), ('IN-OR', 'Odisha'), ('IN-PB', 'Punjab'), ('IN-PY', 'Puducherry'), ('IN-RJ', 'Rajasthan'), ('IN-SK', 'Sikkim'), ('IN-TN', 'Tamil Nadu'), ('IN-TG', 'Telangana'), ('IN-TR', 'Tripura'), ('IN-UT', 'Uttarakhand'), ('IN-UP', 'Uttar Pradesh'), ('IN-WB', 'West Bengal'), ('AU-CT', 'Australian Capital Territory'), ('AU-NS', 'New South Wales'), ('AU-NT', 'Northern Territory'), ('AU-QL', 'Queensland'), ('AU-SA', 'South Australia'), ('AU-TA', 'Tasmania'), ('AU-VI', 'Victoria'), ('AU-WA', 'Western Australia'), ('SG-NA', 'Singapore'), ('EN-NA', 'England'), ('NZ-AL', 'Auckland'), ('NZ-BP', 'Bay of Plenty'), ('NZ-CB', 'Canterbury'), ('NZ-GB', 'Gisborne'), ('NZ-HB', "Hawke's Bay"), ('NZ-MW', 'Manawatu-Whanganui'), ('NZ-NL', 'Northland'), ('NZ-OT', 'Otago'), ('NZ-SL', 'Southland'), ('NZ-TN', 'Taranaki'), ('NZ-WK', 'Waikato'), ('NZ-WT', 'Wellington'), ('NZ-WC', 'West Coast'), ('US-AL', 'Alabama'), ('US-AK', 'Alaska'), ('US-AZ', 'Arizona'), ('US-AR', 'Arkansas'), ('US-CA', 'California'), ('US-CO', 'Colorado'), ('US-CT', 'Connecticut'), ('US-DE', 'Delaware'), ('US-DC', 'District of Columbia'), ('US-FL', 'Florida'), ('US-GA', 'Georgia'), ('US-HI', 'Hawaii'), ('US-ID', 'Idaho'), ('US-IL', 'Illinois'), ('US-IN', 'Indiana'), ('US-IA', 'Iowa'), ('US-KS', 'Kansas'), ('US-KY', 'Kentucky'), ('US-LA', 'Louisiana'), ('US-ME', 'Maine'), ('US-MD', 'Maryland'), ('US-MA', 'Massachusetts'), ('US-MI', 'Michigan'), ('US-MN', 'Minnesota'), ('US-MS', 'Mississippi'), ('US-MO', 'Missouri'), ('US-MT', 'Montana'), ('US-NE', 'Nebraska'), ('US-NV', 'Nevada'), ('US-NH', 'New Hampshire'), ('US-NJ', 'New Jersey'), ('US-NM', 'New Mexico'), ('US-NY', 'New York'), ('US-NC', 'North Carolina'), ('US-ND', 'North Dakota'), ('US-OH', 'Ohio'), ('US-OK', 'Oklahoma'), ('US-OR', 'Oregon'), ('US-PA', 'Pennsylvania'), ('US-PR', 'Puerto Rico'), ('US-RI', 'Rhode Island'), ('US-SC', 'South Carolina'), ('US-SD', 'South Dakota'), ('US-TN', 'Tennessee'), ('US-TX', 'Texas'), ('US-UT', 'Utah'), ('US-VT', 'Vermont'), ('US-VA', 'Virginia'), ('US-WA', 'Washington'), ('US-WV', 'West Virginia'), ('US-WI', 'Wisconsin'), ('US-WY', 'Wyoming')], db_column='state', max_length=5),
        ),
    ]
