# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-21 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_auto_20201026_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_view_reports', 'Can view reports'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
