# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-21 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_managerpermissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managerpermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': (('can_view_reports', 'Can view reports'), ('can_change_system_cost', 'Can change system cost'))},
        ),
    ]
