# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-05-12 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_auto_20210922_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='tier',
            field=models.IntegerField(choices=[('1', 'Tier 1'), ('2', 'Tier 2'), ('3', 'Tier 3')], db_column='tier', default='3'),
        ),
    ]
