# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-06-23 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_city_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPCategory',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MpIndustry',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MpInterestArea',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MPSubcategory',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MPTax',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('rate', models.PositiveIntegerField(db_column='rate')),
            ],
        ),
    ]
