# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-06-23 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_mpcategory_mpindustry_mpinterestarea_mpsubcategory_mptax'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPSolutions',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=150)),
                ('url_structure', models.CharField(db_column='url-structure', max_length=150)),
                ('price', models.FloatField(blank=True, max_length=150)),
                ('about', models.CharField(blank=True, max_length=100000)),
                ('overview', models.CharField(blank=True, max_length=100000)),
                ('how_it_work', models.CharField(blank=True, max_length=100000)),
                ('execution_time', models.CharField(blank=True, max_length=100000)),
                ('short_description', models.CharField(blank=True, default='', max_length=100000)),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='mp_solutions', to='manager.MPCategory')),
                ('sub_category', models.ForeignKey(db_column='subcategory_id', on_delete=django.db.models.deletion.PROTECT, related_name='mp_solutions', to='manager.MPSubcategory')),
                ('tax', models.ForeignKey(db_column='tax_id', on_delete=django.db.models.deletion.PROTECT, related_name='mp_solutions', to='manager.MPTax')),
            ],
        ),
    ]
