# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-06-26 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_mpsolutions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPSolutionImage',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='solution_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='mpsolutions',
            name='url_structure',
            field=models.CharField(db_column='url_structure', max_length=150),
        ),
        migrations.AddField(
            model_name='mpsolutionimage',
            name='solution',
            field=models.ForeignKey(db_column='solution_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='manager.MPSolutions'),
        ),
    ]
