# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-06-23 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_mpsolutions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPSolutionImages',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mp_solution_images', to='manager.MPSolutions')),
            ],
        ),
    ]
