# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-06-26 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_mpsolutionimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpsolutionimages',
            name='solution',
        ),
        migrations.DeleteModel(
            name='MPSolutionImages',
        ),
    ]
