# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-06-26 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_auto_20230626_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpsolutionimage',
            name='solution',
            field=models.ForeignKey(db_column='solution_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='manager.MPSolutions'),
        ),
    ]
