# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-06-26 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_auto_20230626_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpsolutions',
            name='url_structure',
            field=models.CharField(db_column='url_structure', max_length=150),
        ),
    ]
