# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-06-26 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_auto_20230626_1154'),
        ('manager', '0024_auto_20230626_1640'),
    ]

    operations = [
    ]
