# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-06-26 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_merge_20230626_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpsolutionimage',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='./manager/static/solutions'),
        ),
    ]
