# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-06-29 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_auto_20230626_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpsolutions',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
