# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-06-30 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_auto_20230629_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpsolutions',
            name='sub_category',
            field=models.ForeignKey(db_column='sub_category_id', on_delete=django.db.models.deletion.PROTECT, related_name='mp_solutions', to='manager.MPSubcategory'),
        ),
    ]
