# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-06-30 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_auto_20230630_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpsolutionimage',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='mpsolutions',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mpsolutions',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='mpsolutions',
            name='tax',
        ),
        migrations.DeleteModel(
            name='MPSolutionImage',
        ),
        migrations.DeleteModel(
            name='MPSolutions',
        ),
    ]
