# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-01 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_auto_20230630_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPSolution',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('url_structure', models.CharField(db_column='url_strucuture', max_length=200)),
                ('about', models.CharField(db_column='about', max_length=200)),
                ('overview', models.CharField(db_column='overview', max_length=200)),
                ('how_it_work', models.CharField(db_column='how_it_work', max_length=200)),
                ('execution_time', models.CharField(db_column='execution_time', max_length=200)),
                ('short_description', models.CharField(db_column='short_description', max_length=200)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='solutions', to='manager.MPCategory')),
                ('sub_category', models.ForeignKey(db_column='sub_category_id', on_delete=django.db.models.deletion.PROTECT, related_name='solutions', to='manager.MPSubcategory')),
                ('tax', models.ForeignKey(db_column='tax_id', on_delete=django.db.models.deletion.PROTECT, related_name='solutions', to='manager.MPTax')),
            ],
        ),
    ]
