# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-02 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_mpsolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpsolution',
            name='price',
            field=models.PositiveIntegerField(db_column='price', default=0),
        ),
    ]
