# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-02 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0032_auto_20230702_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpsolution',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='mpsolutions', to='manager.MPCategory'),
        ),
        migrations.AlterField(
            model_name='mpsolution',
            name='sub_category',
            field=models.ForeignKey(db_column='sub_category_id', on_delete=django.db.models.deletion.PROTECT, related_name='mpsolutions', to='manager.MPSubcategory'),
        ),
        migrations.AlterField(
            model_name='mpsolution',
            name='tax',
            field=models.ForeignKey(db_column='tax_id', on_delete=django.db.models.deletion.PROTECT, related_name='mpsolutions', to='manager.MPTax'),
        ),
    ]
