# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-02 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0033_auto_20230702_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpsolution',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
    ]
