# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-04 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0035_mpclientprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpclientprofileinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='MPClientProfileInfo',
        ),
    ]
