# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-06 08:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0037_mpsolutionattachement_mpsolutionquestionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPSolutionQuestion',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('question_txt', models.CharField(db_column='question_txt', max_length=1024)),
                ('max_marks', models.PositiveIntegerField(db_column='max_marks')),
                ('sequence', models.PositiveIntegerField(db_column='sequence')),
                ('question_type', models.CharField(choices=[('PLAIN', 'Plain'), ('MUTEX', 'Mutually Exclusive'), ('MULTISELECT', 'Multiple Select')], db_column='question_type', default='PLAIN', max_length=20)),
                ('question_data', django.contrib.postgres.fields.jsonb.JSONField(db_column='question_data', default=dict)),
                ('hide_question', models.BooleanField(db_column='hide_question', default=False)),
                ('optional_comment_required', models.BooleanField(db_column='optional_comment_required', default=False)),
                ('solution', models.ForeignKey(db_column='solution_id', on_delete=django.db.models.deletion.PROTECT, related_name='solutionquestions', to='manager.MPSolution')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.DeleteModel(
            name='MPSolutionAttachement',
        ),
        migrations.DeleteModel(
            name='MPSolutionQuestionnaire',
        ),
    ]
