# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-07 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0038_auto_20230706_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpsolutionquestion',
            name='solution',
        ),
        migrations.DeleteModel(
            name='MPSolutionQuestion',
        ),
    ]
