# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-10 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0040_mpsolutionquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpsolutionquestion',
            name='solution',
            field=models.ForeignKey(blank=True, db_column='solution_id', on_delete=django.db.models.deletion.PROTECT, related_name='solutionquestions', to='manager.MPSolution'),
        ),
    ]
