# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-10 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0042_auto_20230710_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPSolutionProofTagList',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('max_attachment_count', models.IntegerField(db_column='max_attachment_count', default=2)),
                ('created_at', models.DateTimeField(db_column='created_at', null=True)),
                ('proof_tag', models.ForeignKey(db_column='proof_tag_id', on_delete=django.db.models.deletion.PROTECT, related_name='proof_tags_list', to='manager.ProofTag')),
                ('solution', models.ForeignKey(db_column='solution_id', on_delete=django.db.models.deletion.PROTECT, related_name='proof_tags_list', to='manager.MPSolution')),
            ],
        ),
    ]
