# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-10 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0043_mpsolutionprooftaglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPSolutionOtherDetails',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='description', max_length=4096)),
                ('post_approval_description', models.CharField(db_column='post_approval_description', max_length=4096)),
                ('check_points', models.CharField(blank=True, db_column='check_points', max_length=16384)),
                ('audit_fee', models.IntegerField(db_column='earnings_per_audit')),
                ('solution', models.ForeignKey(db_column='solution_id', on_delete=django.db.models.deletion.PROTECT, related_name='other_details', to='manager.MPSolution')),
            ],
        ),
    ]
