# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-10 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0044_mpsolutionotherdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpsolutionprooftaglist',
            name='proof_tag',
            field=models.ForeignKey(db_column='proof_tag_id', on_delete=django.db.models.deletion.PROTECT, related_name='solution_proof_tags_list', to='manager.ProofTag'),
        ),
        migrations.AlterField(
            model_name='mpsolutionprooftaglist',
            name='solution',
            field=models.ForeignKey(db_column='solution_id', on_delete=django.db.models.deletion.PROTECT, related_name='solution_proof_tags_list', to='manager.MPSolution'),
        ),
    ]
