# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-12 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0045_auto_20230710_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpcategory',
            name='image',
            field=models.ImageField(blank=True, db_column='image', upload_to='static/images/category/'),
        ),
        migrations.AddField(
            model_name='mpcategory',
            name='overview',
            field=models.CharField(db_column='overview', default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpcategory',
            name='short_description',
            field=models.CharField(db_column='short_description', default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mpcategory',
            name='url_structure',
            field=models.CharField(db_column='url_structure', default=1, max_length=200),
            preserve_default=False,
        ),
    ]
