# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-13 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0050_auto_20230713_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpcategory',
            name='image',
            field=models.ImageField(blank=True, db_column='image', upload_to='manager/static/images/category/'),
        ),
    ]
