# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-14 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0051_auto_20230713_1538'),
        ('manager', '0052_auto_20230713_1518'),
    ]

    operations = [
    ]
