# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-14 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0053_merge_20230714_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpcategory',
            name='image',
        ),
    ]
