# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-15 05:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0054_remove_mpcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPStore',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='code', default=None, max_length=20, null=True)),
                ('type', models.CharField(blank=True, db_column='type', default='', max_length=20)),
                ('priority', models.CharField(blank=True, db_column='priority', default='', max_length=50)),
                ('name', models.CharField(db_column='name', max_length=500)),
                ('address', models.CharField(db_column='address', max_length=1024)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=100)),
                ('map_location_link', models.CharField(blank=True, db_column='map_location_link', default='', max_length=1024)),
                ('pincode', models.CharField(blank=True, db_column='pincode', default=None, max_length=20, null=True)),
                ('created_at', models.DateTimeField(db_column='created_at', null=True)),
                ('modified_at', models.DateTimeField(db_column='modified_at', null=True)),
                ('city', models.ForeignKey(db_column='city_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.City')),
                ('location', models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.Location')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
