# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-15 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0055_mpstore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpstore',
            name='user',
        ),
    ]
