# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-17 09:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0058_remove_mpstore_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPOrder',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('no_of_response', models.IntegerField(blank=True, db_column='no_of_response', default=1)),
                ('describe', models.CharField(blank=True, db_column='describe', max_length=16384)),
                ('alignment_factors', django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='alignment_factors', default=list)),
                ('store', django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='stores', default=list)),
                ('solution', models.ForeignKey(db_column='solution_id', on_delete=django.db.models.deletion.PROTECT, related_name='mporders', to='manager.MPSolution')),
            ],
        ),
    ]
