# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-18 09:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0059_mporder'),
    ]

    operations = [
        migrations.AddField(
            model_name='mporder',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'Complete'), ('DRAFT', 'Draft'), ('ACTIVE', 'Active')], db_column='status', default='DRAFT', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mporder',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
