# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-21 09:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0060_auto_20230718_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpstore',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
