# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-24 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0061_auto_20230721_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpsolution',
            name='sub_category',
            field=models.ForeignKey(blank=True, db_column='sub_category_id', on_delete=django.db.models.deletion.PROTECT, related_name='mpsolutions', to='manager.MPSubcategory'),
        ),
    ]
