# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-24 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0062_auto_20230724_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpsolution',
            name='about',
        ),
    ]
