# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-24 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0064_auto_20230724_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpsolution',
            name='sub_category',
        ),
    ]
