# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-24 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0065_remove_mpsolution_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpstore',
            name='city',
        ),
        migrations.RemoveField(
            model_name='mpstore',
            name='location',
        ),
        migrations.RemoveField(
            model_name='mpstore',
            name='user',
        ),
        migrations.DeleteModel(
            name='MPStore',
        ),
    ]
