# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-26 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0066_auto_20230724_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpcategory',
            name='overview',
            field=models.CharField(db_column='overview', max_length=16384),
        ),
        migrations.AlterField(
            model_name='mpcategory',
            name='short_description',
            field=models.CharField(db_column='short_description', max_length=16384),
        ),
        migrations.AlterField(
            model_name='mpsolution',
            name='execution_time',
            field=models.CharField(db_column='execution_time', max_length=16384),
        ),
        migrations.AlterField(
            model_name='mpsolution',
            name='how_it_work',
            field=models.CharField(db_column='how_it_work', max_length=16384),
        ),
        migrations.AlterField(
            model_name='mpsolution',
            name='overview',
            field=models.CharField(db_column='overview', max_length=16384),
        ),
        migrations.AlterField(
            model_name='mpsolutionotherdetails',
            name='audit_fee',
            field=models.IntegerField(db_column='earnings_per_audit', default=0),
        ),
        migrations.AlterField(
            model_name='mpsolutionotherdetails',
            name='description',
            field=models.CharField(db_column='description', max_length=16384),
        ),
        migrations.AlterField(
            model_name='mpsolutionotherdetails',
            name='post_approval_description',
            field=models.CharField(db_column='post_approval_description', max_length=16384),
        ),
    ]
