# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-08-01 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0068_auto_20230731_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='mporder',
            name='price',
            field=models.IntegerField(db_column='price', default=0, max_length=20),
        ),
    ]
