# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-08-01 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0069_mporder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpsolution',
            name='is_popular',
            field=models.BooleanField(db_column='is_popular', default=False),
        ),
        migrations.AlterField(
            model_name='mporder',
            name='price',
            field=models.IntegerField(db_column='price', max_length=20),
        ),
        migrations.AlterField(
            model_name='mpsolution',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='mpsolutions', to='manager.MPCategory'),
        ),
    ]
