# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-08-01 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0070_auto_20230801_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MPSubcategory',
        ),
        migrations.RemoveField(
            model_name='mpsolution',
            name='category',
        ),
    ]
