# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-08-01 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0071_auto_20230801_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPSolutionCategoryDetails',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('category', models.ForeignKey(blank=True, db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='mpsolutioncategorydetails', to='manager.MPCategory')),
                ('solution', models.ForeignKey(blank=True, db_column='solution_id', on_delete=django.db.models.deletion.PROTECT, related_name='mpsolutioncategorydetails', to='manager.MPSolution')),
            ],
        ),
    ]
