# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-08-03 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0072_mpsolutioncategorydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpsolution',
            name='short_description',
            field=models.CharField(db_column='short_description', max_length=16384),
        ),
    ]
