# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-08-04 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0073_auto_20230803_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mporder',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='mporder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
        migrations.DeleteModel(
            name='MPOrder',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
