# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-08-22 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0075_auto_20230809_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpsolution',
            name='audit_type',
            field=models.CharField(choices=[('WALKIN', 'Walkin'), ('PHONE', 'Phone'), ('WEB', 'Web'), ('VISIBILITY', 'Visibility'), ('COMPETITION', 'Competition'), ('SERVICE', 'Service'), ('SALES', 'Sales'), ('FINE_DINE', 'Fine Dine'), ('SKY_KARTING', 'Sky Karting'), ('SMAAASH_ARENA', 'Smaaash Arena'), ('GENERAL', 'General'), ('SMAAASH', 'Smaaash'), ('SMAAASH_MEGA', 'Smaaash Mega'), ('SMAAASH_ZONE', 'Smaaash Zone'), ('DDC', 'Ddc'), ('HTC', 'Htc'), ('ASCVD', 'Ascvd'), ('SKIN_HYDRATION', 'Skin Hydration'), ('HYPER_PIGMENTATION', 'Hyper Pigmentation'), ('SKIN_SENSITIVE', 'Skin Sensitive'), ('RETAIL', 'Retail')], db_column='type', default='Walkin', max_length=20),
            preserve_default=False,
        ),
    ]
