# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-08-25 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0077_auto_20230822_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpsolution',
            name='name',
            field=models.CharField(db_column='name', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='mpsolution',
            name='url_structure',
            field=models.CharField(db_column='url_strucuture', max_length=200, unique=True),
        ),
    ]
