# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-08-25 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0078_auto_20230825_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpsolution',
            name='short_description',
            field=models.CharField(db_column='short_description', max_length=230),
        ),
    ]
