# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-09-21 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0081_auto_20230831_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpcategory',
            name='url_structure',
            field=models.CharField(db_column='url_structure', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='mpsolution',
            name='url_structure',
            field=models.CharField(db_column='url_structure', max_length=200, unique=True),
        ),
    ]
