# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-09-21 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0082_auto_20230921_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpsolution',
            name='is_show',
            field=models.BooleanField(db_column='is_show', default=False),
        ),
    ]
