# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-12-04 08:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0083_mpsolution_is_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerProfileInfo',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('mobile', models.CharField(blank=True, db_column='mobile', max_length=15, null=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
