# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-12-05 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0084_managerprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofileinfo',
            name='name',
            field=models.CharField(blank=True, db_column='name', max_length=25, null=True),
        ),
    ]
