# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-12-05 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0085_managerprofileinfo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerprofileinfo',
            name='name',
        ),
    ]
