# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-01-17 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0088_auto_20231212_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofileinfo',
            name='is_admin',
            field=models.NullBooleanField(db_column='admin', default=False),
        ),
    ]
