# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-01-17 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0089_managerprofileinfo_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerprofileinfo',
            name='is_admin',
            field=models.BooleanField(db_column='admin', default=False),
        ),
    ]
