# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-02-12 10:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0090_auto_20240117_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditProoftag',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('description', models.CharField(blank=True, db_column='description', max_length=5000)),
                ('prooftag', models.ForeignKey(blank=True, db_column='prooftag_id', on_delete=django.db.models.deletion.CASCADE, related_name='prooftag', to='manager.ProofTag')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
