# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-02-12 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0092_remove_auditprooftag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditprooftag',
            name='description',
        ),
        migrations.RemoveField(
            model_name='auditprooftag',
            name='prooftag',
        ),
        migrations.AddField(
            model_name='auditprooftag',
            name='proof_tag_id',
            field=models.ForeignKey(blank=True, db_column='proof_tag_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.ProofTag'),
        ),
        migrations.AddField(
            model_name='auditprooftag',
            name='prooftagTextareaValue',
            field=models.CharField(blank=True, db_column='prooftagTextareaValue', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='auditprooftag',
            name='user',
            field=models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
