# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-02-19 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0093_auto_20240212_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditprooftag',
            name='proof_tag_id',
        ),
        migrations.RemoveField(
            model_name='auditprooftag',
            name='user',
        ),
        migrations.DeleteModel(
            name='AuditProoftag',
        ),
    ]
