# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-02-20 12:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0094_auto_20240219_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditProoftagNotAvailable',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('prooftagTextareaValue', models.CharField(blank=True, db_column='prooftagTextareaValue', max_length=5000, null=True)),
                ('proof_tag_id', models.ForeignKey(blank=True, db_column='proof_tag_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.ProofTag')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
