# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-02-20 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0095_auditprooftagnotavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditprooftagnotavailable',
            name='audit_store_id',
            field=models.IntegerField(blank=True, db_column='audit_store_id', null=True),
        ),
    ]
