# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-02-22 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0096_auditprooftagnotavailable_audit_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditprooftagnotavailable',
            name='proof_tag_id',
            field=models.IntegerField(blank=True, db_column='proof_tag_id', null=True),
        ),
    ]
