# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-02-22 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0097_auto_20240222_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditprooftagnotavailable',
            name='proof_tag_id',
        ),
        migrations.AddField(
            model_name='auditprooftagnotavailable',
            name='audit_cycle_prooftag_list',
            field=models.IntegerField(blank=True, db_column='audit_cycle_prooftag_list', null=True),
        ),
    ]
