# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-05-08 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0099_auto_20240408_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpsolution',
            name='price',
        ),
        migrations.AddField(
            model_name='mpsolution',
            name='price_INR',
            field=models.PositiveIntegerField(db_column='price_INR', default=0),
        ),
        migrations.AddField(
            model_name='mpsolution',
            name='price_USD',
            field=models.PositiveIntegerField(db_column='price_USD', default=0),
        ),
    ]
