# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2025-01-03 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0103_auto_20250103_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditprooftagnotavailable',
            name='prooftagTextareaValue',
        ),
        migrations.AddField(
            model_name='auditprooftagnotavailable',
            name='description',
            field=models.CharField(blank=True, db_column='description', max_length=5000, null=True),
        ),
    ]
