# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-02-09 12:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0105_auto_20250414_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofileinfo',
            name='allowed_countries',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='allowed_countries', default=list, null=True),
        ),
    ]
