# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2026-06-23 07:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0107_auto_20260612_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorProfileInfo',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, db_column='mobile', max_length=15, null=True)),
                ('firm_name', models.CharField(blank=True, db_column='firm_name', max_length=255, null=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerProfileInfo',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, db_column='mobile', max_length=15, null=True)),
                ('firm_name', models.CharField(blank=True, db_column='firm_name', max_length=255, null=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
